# Calculando Autovalores e Autovetores
#### Este progama pretendo mostrar um recurso computacional para conseguir calcular autovalores e autovetores a partir de uma matriz de transformação informada. Associados com uma transformação linear T estão os seus autovetores, que, como veremos, são direções especiais para esta transformação T. Por esta razão, são também conhecidos como vetores próprios ou vetores característicos de T. Aparecem em muitas aplicações, pois nos ajudam a entender mais profundamente a transformação linear T.

##### Referência: Álgebra Linear com aplicações / Anton Howard e Chris Rorres; trad. Claus Ivo Doering. - 8. ed. - Porto Alegre: Bookman, 2001.

> Se A é uma matriz $n_{x}n$, então um vetor não-nulo **x** em $R^{n}$ é chamado um **autovetor** de A se A**x** é um múltiplo escalar de **x**, ou seja, A**x** = &lambda;**x** para algum escalar &lambda;. O escalar &lambda; é chamado um **autovalor** de A e dizemos que **x** é um **autovetor** associado a &lambda;.

Em $R^{2}$ e $R^{3}$, a multiplicação por A manda cada autovetor **x** de A (se houver) sobre a mesma reta pela origem que **x**. Dependendo do sinal e da magnitude do autovalor &lambda; associado a **x**, o operador linear A**x** = &lambda;**x** comprime ou estica **x** por um fator &lambda;, invertendo o sentido no caso de &lambda; negativo.

In [5]:
# importando a biblioteca numpy do Python
import numpy as np 

print("Progama que calcula Autovalores e Autovetores.\n")

# quantidade de linhas da matriz de transformação
linha = int(input("Informe a quantidade de linhas da matriz de transformação: "))

#quantidade de colunas da matriz de transformação
coluna = int(input("Informe a quantidade de colunas da matriz de transformação: "))

# inicializando uma matriz com as dimensões adequadas e de números reais
matriz = np.empty([linha, coluna], dtype = float)

# indo para a próxima linha
print("\n")

# estrutura de repetição for usada para preencher os elementos da matriz
for i in range(0, linha):
    for j in range(0, coluna):
        matriz[i][j] = float(input("Informe o elemento [{}][{}] da matriz: ".format(i + 1, j + 1)))

# imprime a matriz na tela
print("\n\nA matriz digitada é:\n\n{}".format(matriz))

if(np.linalg.det(matriz) != 0):
    
    # função responsável por receber os autovalores e autovetores da matriz de transformação
    (autovalores,autovetores) = np.linalg.eig(matriz)
    matrizDiagonal = np.diag(autovalores) # calcula a matriz diagona de autovalores
    
    # imprime na tela os autovalores
    print("\n\nAutovalores:\n\n{}\n\n".format(autovalores))

    # imprime na tela a matriz diagonal de autovalores
    print("Matriz Diagonal de autovalores:\n\n{}\n\n".format(matrizDiagonal))

    # imprime na tela os autovetores
    print("cada coluna é associada a cada um dos autovalores, respectivamente.")
    print("Autovetores:\n\n{}".format(autovetores))
else:
    print("\nA matriz não é invertível, dado que det(matriz) == 0.")

Progama que calcula Autovalores e Autovetores.



Informe a quantidade de linhas da matriz de transformação:  3
Informe a quantidade de colunas da matriz de transformação:  3


Informe o elemento [1][1] da matriz:  3
Informe o elemento [1][2] da matriz:  -1
Informe o elemento [1][3] da matriz:  1
Informe o elemento [2][1] da matriz:  -1
Informe o elemento [2][2] da matriz:  5
Informe o elemento [2][3] da matriz:  -1
Informe o elemento [3][1] da matriz:  1
Informe o elemento [3][2] da matriz:  -1
Informe o elemento [3][3] da matriz:  3




A matriz digitada é:

[[ 3. -1.  1.]
 [-1.  5. -1.]
 [ 1. -1.  3.]]


Autovalores:

[6. 2. 3.]


Matriz Diagonal de autovalores:

[[6. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


cada coluna é associada a cada um dos autovalores, respectivamente.
Autovetores:

[[-4.08248290e-01  7.07106781e-01  5.77350269e-01]
 [ 8.16496581e-01  5.21597494e-16  5.77350269e-01]
 [-4.08248290e-01 -7.07106781e-01  5.77350269e-01]]


- Se A é uma matriz $n_{x}n$ e se $T_{A}:R^{n}$ &rarr; $R^{n}$ é a multiplicação por A, então as seguintes afirmações são equivalentes:

|**Afirmações Equivalente**|
|:------------:|
|1. A é invertível. |
|2. A**x** = 0 admite somente a solução trivial.|
|3. A forma escalonada reduzida por linha de A é $I_{n}$.|
|4. A pode ser escrita como um produto de matrizes elementares.|
|5. A**x** = **b** é consistente para cada matriz **b** de tamanho $n_{x}1$.|
|6. A**x** = **b** tem exatamente uma solução para cada matrix **b**  de tamanho $n_{x}n$.|
|7. det(A) &ne; 0.|
|8. A imagem de $T_{A}$ é o $R^{n}$.|
|9. $T_{A}$ é injetora.|
|10. Os vetores-coluna de A são linearmente independentes.|
|11. Os vetores-linhas de A são linearmente dependentes.|
|12. Os vetores-coluna de A geram o $R^{n}$.|
|13. Os vetores-linhas de A geram o $R^{n}$.|
|14. Os vetores-coluna de A formam uma base do $R^{n}$.|
|15. Os vetores-linha de A formam uma base do $R^{n}$.|
|16. A tem posto n.|
|17. A tem nulidade 0.|
|18. O complemento ortogonal do espaço-nulo  de A é o $R^{n}$.|
|19. O complemento ortogonal do espaço-linha de A é {0}.|
|20. $A^{t}A$ é invertível.|
|21. &lambda; = 0 não é um autovalor de A.|

### Alguma Dúvida? Entre em Contato Comigo:

- [Me envie um e-mail](mailto:alysson.barbosa@ee.ufcg.edu.br);