# Estudando a Biblioteca Numpy

#### Neste notebook, vamos analisar algumas funções pertencentes a biblioteca numpy. É pertinente saber que tal biblioteca nos permite implementar ótimas aplicações computacionais em Àlgebra Linear e, através dela, reduzir o nosso trabalho em diversas situações na qual o cálculo feito de forma manual seja algo maçante.

In [1]:
import numpy as np # importando a biblioteca de funções do python

##### Criando uma Matriz

In [2]:
M = np.array([10,24,34,45,56]) # iniciando um array em python

##### Verificando o Tipo da Variável

In [3]:
type(M) #mostra o tipo da variável a qual a função type recebe

numpy.ndarray

##### Formas de Imprimir Dados na Tela


In [4]:
print("{}".format(M)) # pode-se imprimir algum tipo de dado dessa forma

[10 24 34 45 56]


In [5]:
M # digitar a variável no Jupyter Notebook também nos permite ver o seu conteúdo

array([10, 24, 34, 45, 56])

In [6]:
print(M) # colocar uma variável diretamente também é um formato compilável

[10 24 34 45 56]


##### Trabalhando com Elementos da Matriz

In [7]:
print("{}".format(M[0])) 
# atente-se que na progamação, na maioria das linguagens temos um array iniciado no elemento [0][0] 

10


In [8]:
print("{}".format(M[4])) # aqui vemos o elemento 4, na terceira possição do array

56


In [9]:
print("{}".format(M[0:4])) 
# mostra todos os elementos do array começando na posição zero até a terceira posição
# atente-se que o último elemento de parada não é considerado no cálculo, e sim o seu antecessor

[10 24 34 45]


##### Dimensões da Matriz

In [10]:
print(M.shape) 
# função que mostra a dimensão do array
# (linhas, colunas)

(5,)


##### Matrizes de Tamanhos Diversos (arrays multidimensionais)

In [11]:
MD = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # criando um array multidimensional

In [12]:
print("{}".format(MD)) # imprime o array multidimensional

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
MD.shape # verificando a dimensão do array

(2, 5)

In [14]:
MD[1,1] # forma de verificar os elementos da matriz multidimensional

7

In [15]:
MD[1][1] # outra forma de verificar os elementos da matriz multidimensional

7

In [16]:
MD.shape[0] # o parâmetro de entrada zero permitirá ver a quantidade de linhas do array

2

In [17]:
MD.shape[1] # o parâmetro de entrada um permitirá ver a quantidade de colunas do array

5

##### Criando uma Submatriz de Outra Matriz

In [18]:
subMD = MD[0:2, 0:3] 
# subMD recebe as linhas localizadas na posição zero e um, e colunas de zero a dois
# atente-se que o último digito de parada é desconsiderado

In [19]:
print("{}".format(subMD)) # imprime a matriz subMD

[[1 2 3]
 [6 7 8]]


##### Modificando Elementos das Matrizes

In [20]:
MD[1,1] = 11 # nova entrada para o elemento da matriz localizado na posição MD[1][1]

In [21]:
print("{}".format(MD)) # veja como o elemento da matriz na posição [1][1] foi modificado

[[ 1  2  3  4  5]
 [ 6 11  8  9 10]]


##### Transformando uma Matriz de Números Inteiros em Números Reais

In [22]:
MR = np.array([[1.0,2,3,4,5], [1000,12,4556,788,1], [6,7,8,9,1000]])
# o fato do primeiro elemento ser um float, número real, indica que todos os outros elementos serão também do tipo float

In [23]:
print("{}".format(MR)) # imprime a matriz MR
# Os valores dos elementos da matriz são mostrados no formato de notação científica computacional

[[1.000e+00 2.000e+00 3.000e+00 4.000e+00 5.000e+00]
 [1.000e+03 1.200e+01 4.556e+03 7.880e+02 1.000e+00]
 [6.000e+00 7.000e+00 8.000e+00 9.000e+00 1.000e+03]]


##### Criando uma Matriz Identidade


In [24]:
I = np.eye(4) #observe que a matriz identidade será do tipo float
# o parâmetro de entrada é a ordem da matriz a ser trabalhada

In [25]:
print("{}".format(I)) # imprime a matriz Identidade I

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


##### Criando uma Matriz de Zeros


In [26]:
Z = np.zeros((4,4)) # interessante para inicializar uma matriz sem lixo de memória
# são dois parâmetros de entrada, relativos a quantidade de linhas e colunas, respectivamente.
# caso tal matriz seja manipulada por algum procedimento de multiplicação, essa inicialização não é uma boa escolha

In [27]:
print("{}".format(Z)) # imprimindo a matriz Z

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


##### Criando uma Matriz de Uns

In [28]:
U = np.ones((4,2)) 
# mesma ideia da função acima, mas ao invés de zeros, será preenchido com valores 1
# observe que essa matriz é ideal quando trabalha-se com operações de multiplicação

In [29]:
print("{}".format(U)) # imprime a matriz U

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [30]:
10 * U
# multiplicando uma matriz com todos os elementos iniciados com 1 por um escalar

array([[10., 10.],
       [10., 10.],
       [10., 10.],
       [10., 10.]])

Ou

In [31]:
U = np.full((5,2), 10)
# função que cria um array em que todos os seus elementos são iguais a uma constante a ser definida
# np.full((número de linhas, número de colunas), constante a ser definida na matriz)

In [32]:
print("{}".format(U)) #imprime a matriz U

[[10 10]
 [10 10]
 [10 10]
 [10 10]
 [10 10]]


##### Matriz Randômica

In [33]:
R = np.random.random((4,5)) # np.random.random((número de linhas, número de colunas))
# cria uma matriz de números aleatórios

In [34]:
print("{}".format(R)) # imprime a matriz R

[[0.44672864 0.72232289 0.01232689 0.06576017 0.98499059]
 [0.9377346  0.34222689 0.8584688  0.97704743 0.38100834]
 [0.33374236 0.81985432 0.5370455  0.28956349 0.94895315]
 [0.18477957 0.87425711 0.71618074 0.66404689 0.61337039]]


##### Média dos Elementos da Matriz

In [35]:
X = np.array([[1,2,3],[4,5,6]]) # criando uma matriz X

In [36]:
np.mean(X) # calcula a média de todos os elementos da matriz X inicializada acima

3.5

##### Operações com Matrizes

In [37]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) # criando uma matriz A
B = np.array([[-1,0,1],[0,1,1],[4,4,4]]) # criando uma matriz B

In [38]:
print("{}".format(A)) # imprime a matriz A

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
print("{}".format(B)) # imprime a matriz B

[[-1  0  1]
 [ 0  1  1]
 [ 4  4  4]]


In [40]:
A * B 
# multiplicação simples de uma matriz
# OBS: só é permitido a entrada de matrizes de mesma ordem

array([[-1,  0,  3],
       [ 0,  5,  6],
       [28, 32, 36]])

In [41]:
A + B # soma duas matrizes de mesma ordem

array([[ 0,  2,  4],
       [ 4,  6,  7],
       [11, 12, 13]])

In [42]:
A - B # subtração de duas matrizes de mesma ordem

array([[2, 2, 2],
       [4, 4, 5],
       [3, 4, 5]])

In [43]:
B - A # subtração de duas matrizes de mesma ordem

array([[-2, -2, -2],
       [-4, -4, -5],
       [-3, -4, -5]])

>Podemos realizar operações utilizando a biblioteca do numpy. Um motivo para essa escolha é que podemos realizar multiplicações com matrizes de ordens diferentes, mas definidas na operação. Além disso, pode-se mudar o tipo de dados trabalhados na matriz e ainda especificar a quantidade de bytes suportadas para armazenamento de cada elemento da mesma. (Dependência dos requisitos da máquina trabalhada, mas em geral: 16 - 128 bytes).

In [44]:
np.multiply(A,B, dtype = float) # multiplicação de matrizes de ordem diferentes, mas com a multiplicação definida

array([[-1.,  0.,  3.],
       [ 0.,  5.,  6.],
       [28., 32., 36.]])

In [45]:
np.add(A,B, dtype = np.float16) # soma as matrizes de mesma ordem

array([[ 0.,  2.,  4.],
       [ 4.,  6.,  7.],
       [11., 12., 13.]], dtype=float16)

In [46]:
np.subtract(A,B, dtype = np.int32) # subtrai as matrizes de mesma ordem

array([[2, 2, 2],
       [4, 4, 5],
       [3, 4, 5]])

In [47]:
np.subtract(B,A, dtype = np.int32) # subtrai as matrizes de mesma ordem

array([[-2, -2, -2],
       [-4, -4, -5],
       [-3, -4, -5]])

In [48]:
A = np.array([[1,2,3],[4,5,6]]) # criando a matriz A
B = np.array([[1],[1],[1]]) # criando a matriz B

In [49]:
np.matmul(A,B) #outra função que realiza a multiplicação de matrizes de ordens diferentes, mas sem especificador de tipo

array([[ 6],
       [15]])

In [50]:
np.matmul(B,A) #Matriz com operação não definida, veja que a compilação não ocorrerá

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

> Cuidado, pois mesmo o código estando digitado corretamente, operações matemáticas podem não estar definidas, resultando em erros fatais ou não fatais pelo compilador.

In [51]:
np.dot(A,B) # outra forma de multiplicar duas matrizes

array([[ 6],
       [15]])

In [52]:
a = np.array([[1,2,3]]) # criando a matriz a
b = np.array([[4,5,6]]) # criando a matriz b

In [53]:
np.inner(a,b) 
#Um produto interno é uma generalização do produto escalar. Em um espaço vetorial, é uma maneira de multiplicar vetores 
# juntos, com o resultado dessa multiplicação sendo um escalar.

array([[32]])

In [54]:
A = np.array([[1,2,3],[3,4,5]]) # criando a matriz A
B = np.array([[1,5,7],[5,9,9]]) # criando a matriz B

In [55]:
np.tensordot(A,B) # produto tensorial de dois espaços vetoriais

array(128)

In [56]:
A = np.array([[1,2,7],[3,6,7],[8,9,0]]) # criando a matriz A

In [57]:
np.linalg.matrix_power(A,5) # função responsável por calcular a potenciação de matrizes.
# Nesse caso, A está elevada a 5º potência

array([[123235, 185759, 175273],
       [205065, 300027, 255535],
       [221333, 307524, 210945]])

##### Produto Kronecker

In [58]:
A = np.array([[1,2],[3,4]]) # criando a matriz A
B = np.array([[0,5],[6,7]]) # criando a matriz B

In [59]:
np.kron(A,B) # calcula o produto kronecker de duas matrizes

array([[ 0,  5,  0, 10],
       [ 6,  7, 12, 14],
       [ 0, 15,  0, 20],
       [18, 21, 24, 28]])

##### Fatoração de Cholesky

In [60]:
A = np.array([[4,12,-16],[12,37,-43],[-16,-43,98]]) # criando a matriz A

In [61]:
fatorada = np.linalg.cholesky(A) # função responsável por calcular a fatoração de cholesky

In [62]:
fatorada # imprime a matriz A

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])

In [63]:
np.matmul(fatorada,fatorada.transpose()) #provando a validade da Fatoração de Cholesky em python
# multiplica a matriz fatorada por sua transposta, obtendo a matriz A que foi fatorada

array([[  4.,  12., -16.],
       [ 12.,  37., -43.],
       [-16., -43.,  98.]])

In [64]:
A = np.array([[2,0],[0,1]]) # criando uma matriz A

In [65]:
A # imprime a matriz A

array([[2, 0],
       [0, 1]])

##### Autovalores e Autovetores

In [66]:
(autovalores, autovetores) = np.linalg.eig(A) #determinando autovalores e autovetores
matrizDiagonal = np.diag(autovalores) #matriz diagonal de autovalores

A = np.matmul(np.matmul(autovetores,matrizDiagonal),np.linalg.inv(autovetores)) # A = PDP^(-1)
# obtendo novamente a matriz A através da decomposição espectral ou valores singulares

In [67]:
autovetores # autovetores da matriz A

array([[1., 0.],
       [0., 1.]])

In [68]:
matrizDiagonal # matriz diagonal

array([[2., 0.],
       [0., 1.]])

In [69]:
A # matriz de transformação linear

array([[2., 0.],
       [0., 1.]])

In [70]:
autovalores # autovalores para a matriz A

array([2., 1.])

In [71]:
np.linalg.eigvals(A) # outra forma de se obter os autovalores

array([2., 1.])

##### Decomposição em Valores Singulares

In [72]:
A = np.array([[2,0],[0,1]]) # criando uma matriz A
(U,s,V) = np.linalg.svd(A)

In [73]:
U # imprime a matriz U 

array([[1., 0.],
       [0., 1.]])

In [74]:
s # imprime a matriz s

array([2., 1.])

In [75]:
V # imprime a matriz V

array([[1., 0.],
       [0., 1.]])

##### Determinante de Matrizes


In [76]:
np.linalg.det(A) # determinante da matriz

2.0

##### Posto da Matriz

In [77]:
np.linalg.matrix_rank(A) #posto da matriz

2

##### Traço da Matriz (Soma da Diagonal)

In [78]:
np.trace(A) #traço da matriz (soma da diagonal)

3

##### Sistema de Equações

In [79]:
# Vamos considerar Ax = B
A = np.array([[3], [4]]) # criando a matriz A
b = np.array([[6], [8]]) # criando a matriz b
# 3x = 6
# 4y = 8

In [80]:
X = np.matmul(np.linalg.pinv(A), b)
# realiza a multiplicação da matriz inversa de A com a matriz b

In [81]:
X # imprime a matriz X

array([[2.]])

##### Matriz Inversa

In [82]:
A = np.array([[1,2],[3,4]]) # criando a matriz A

In [83]:
np.linalg.pinv(A) # imprime a matriz inversa

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

|**_Aprenda mais_**                                                                                                       |
|-------------------------------------------------------------------------------------------------------------------------|
|- _[numpy.org](https://numpy.org/)_                                                                                      |
|- _[scipy.org](https://www.scipy.org/)_                                                                                  |
|- _[Listas de Exercícios - Álgebra Linear (prof. Edmar Candeia Gurjão)](http://ecandeia.dee.ufcg.edu.br/disciplinas)_    |