# Teoria dos Grafos
#### Vamos utilizar representações matriciais das relações entre elementos de um conjunto e, através de arítimética matricial, vamos analisar essas relações.

##### Referência: Álgebra Linear com aplicações / Anton Howard e Chris Rorres; trad. Claus Ivo Doering. - 8. ed. - Porto Alegre: Bookman, 2001.

### Relações entre membros do conjunto

Existem inúmeros exemplos de conjuntos com um número finito de elementos nos quais existe alguma relação entre os elementos do conjunto. Por exemplo, o conjunto poderia consistir de uma coleção de pessoas, animais, países, companhias, equipes esportivas ou cidades; e a relação entre dois elementos A e B de um tal conjunto poderia ser que a pessoa A domina a pessoa B, o animal A alimenta-se do animal B, o país A apoia militarmente o país B, A companhia A vende seus produtos para a companhia B, a equipe A derrota sistematicamente a equipe B ou a cidade A possui um vôo sem escalas para a cidade B.

### Exemplo: Influências numa família

Uma certa família consiste de uma mãe, um pai, uma filha e dois filhos. Os membros da família exercem influência, ou poder, sobre os outros membros da família da seguinte maneira: a mãe pode influenciar a filha e o filho mais velho; o pai pode influenciar os dois filhos; a filha pode influenciar o pai; o filho mais velho pode influenciar o filho mais novo; o filho mais novo pode influenciar a mãe.

Vamos moldar essa ideia de influência:

$\begin{bmatrix}
           [] & Mae & Pai & Filha & Filho Velho & Filho Novo \\
          Mae & 0 & 0 & 1 & 1 & 0 \\
          \end{bmatrix}$

$\begin{bmatrix}
           [] & Mae & Pai & Filha & Filho Velho & Filho Novo \\
          Pai & 0 & 0 & 0 & 1 & 1 \\
          \end{bmatrix}$

$\begin{bmatrix}
            []  & Mae & Pai & Filha & Filho Velho & Filho Novo \\
          Filha & 0 & 1 & 0 & 0 & 0 \\
          \end{bmatrix}$

$\begin{bmatrix}
              []      & Mae & Pai & Filha & Filho Velho & Filho Novo \\
          Filho Velho & 0 & 0 & 0 & 0 & 1 \\
          \end{bmatrix}$

$\begin{bmatrix}
              []     & Mae & Pai & Filha & Filho Velho & Filho Novo \\
          Filho Novo & 1 & 0 & 0 & 0 & 0 \\
          \end{bmatrix}$

As entradas em 1 indicam o poder de influência que o objeto da linha tem sobre a coluna, e o 0 é a ausência de influência.

A partir disso, podemos montar a matriz:

$$\begin{bmatrix}
         [] & M & P & FA & FV & FN \\
          M & 0 & 0 & 1 & 1 & 0 \\
          P & 0 & 0 & 0 & 1 & 1 \\
          FA & 0 & 1 & 0 & 0 & 0 \\
          FV & 0 & 0 & 0 & 0 & 1 \\
          FN & 1 & 0 & 0 & 0 & 0 \\
          \end{bmatrix}$$

In [39]:
# importando a biblioteca numpy do Python
import numpy as np 

In [40]:
# definindo a matriz influenciaFamilia
influenciaFamilia = np.array([[0,0,1,1,0],[0,0,0,1,1],[0,1,0,0,0],[0,0,0,0,1],[1,0,0,0,0]]) 

In [41]:
# imprimindo a matriz influenciaFamilia
print("A matriz de influência familiar é:\n\n{}".format(influenciaFamilia))

A matriz de influência familiar é:

[[0 0 1 1 0]
 [0 0 0 1 1]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]]


Por definição as matrizes obedecerão as seguintes propiedades:

1. Todas entradas são 0 ou 1.

2. Todas entradas na diagonal principal são 0.

No exemplo 1, o pai não pode influenciar diretamente a mãe, ou seja $P -> M$ não é verdadeiro. Mas o pai pode influenciar o filho mais novo, que por sua vez pode influenciar a mãe. Nós escrevemos isto $P -> FN -> M$ e chamamos conexão de de 2 passos de P para M. Analogamente, chamamos $M -> FV$ de conexão de 1 passo, $FA -> FV -> FN -> M$ de conexão de 3 passos, e assim por diante. Vamos considerar, agora, uma técnica para encontrar o número de todas as conexões de r passos (r = 1,2...) de um vértice $P_{i}$ para um vértice $P_{j}$ de um grafo dirido qualquer. (Isto incluirá o caso em que $P_{i}$ e $P_{j}$ são o mesmo vértice). O número de conexões de 1 passo de $P_{i}$ para $P_{j}$ é simplesmente $M{ij}$. Ou seja, há somente zero ou uma conexão de 1 passo de $P_{i}$ para $P_{j}$, dependendo se $m_{ij}$  é zero ou um. Para o número de conexões de 2 passos, nós consideramos o quadrado da matriz de vértices. Se $m_{ij}^{(2)}$ é o (i,j)-ésimo elemento de $M^2$, nós temos:

- $m_{ij}^{(2)} = m_{i1}m_{1j} + m_{i2}m_{2j} + ... + m_{in}m_{nj}$

Agora, se $m_{i1} = m_{1j} = 1$, existe uma conexão de 2 passos $P_{i} -> P_{1} -> P_{j}$ de $P_{i}$ para $P_{j}$. No entanto, se $m_{i1}$ ou se $m_{1j}$ é zero, uma tal conexão de 2 passos não é possível. Assim, $P_{i} -> P_{1} -> P_{j}$ é uma conexão de 2 passos se, e somente se, $m_{i1}m_{1j} = 1$. Similarmente, para cada $k = 1, 2,...,n,P_{i} -> P_{k} -> P_{j}$ é uma conexão de 2 passos de $P_{i}$ para $P_{j}$ se, e somente se, o termo $m_{ik}m_{kj}$ é igual a um; caso contrário, o termo é zero.

Um argumento semelhante funcionará para encontrar o número de conexões de 3,4,...,n passos de $P_{i}$ para $P_{j}$.

### Teorema:

> Seja M a matriz de vértices de um grafo dirigido e seja $m_{ij}^{(r)}$ o (i,j)-ésimo elemento de $M^{r}$. Então $m_{ij}^{(r)}$ é igual ao número de conexões de r passos de $_{i}$ para $P_{j}$.

Vamos utilizar o exemplo acima para ver, qual familiar pode influenciar outrem, de forma indireta.

### Exemplo: Influência na Família por 2 passos

In [42]:
# calcula a matriz elevada a segunda potência.
influenciaFamilia_2passos = np.linalg.matrix_power(influenciaFamilia, 2) 

In [43]:
print("A matriz com 2 passos é:\n\n{}".format(influenciaFamilia_2passos)) 
# a matriz abaixo informa quantos caminhos há para se influenciar outra pessoa em 2 passos,
# levando a consideração que a ordem de influência é da linha para a coluna

A matriz com 2 passos é:

[[0 1 0 0 1]
 [1 0 0 0 1]
 [0 0 0 1 1]
 [1 0 0 0 0]
 [0 0 1 1 0]]


Observe que agora temos uma nova matriz de influência, essa que ocorrerá por dois passos. Veja o caso discutido acima sobre influência indireta para esse exemplo e observe como a teoria funcionou na prática.

### Exemplo: Influência na Família por 3 passos

In [44]:
# calcula a matriz elevada a terceira potência.
influenciaFamilia_3passos = np.linalg.matrix_power(influenciaFamilia,3) 

In [45]:
print("a matriz com 3 passos é:\n\n{}".format(influenciaFamilia_3passos)) 
# a matriz abaixo informa quantos caminhos a para se influenciar outra pessoa em 2 passos,
# levando a consideração que a ordem de influência é da linha para a coluna

a matriz com 3 passos é:

[[1 0 0 1 1]
 [1 0 1 1 0]
 [1 0 0 0 1]
 [0 0 1 1 0]
 [0 1 0 0 1]]


### Exemplo: Rota Aérea

A matriz abaixo representa o mapa de uma pequena companhia aére que atende a quatro cidades $P_{1}$,$P_{2}$,$P_{3}$ e $P_{4}$. Como grafo dirigido, a matriz é:

$$\begin{bmatrix}
                 & P_{1} & P_{2} & P_{3} & P_{4} \\
           P_{1} & 0 & 1 & 1 & 0 \\
           P_{2} & 1 & 0 & 1 & 0 \\
           P_{3} & 1 & 0 & 0 & 1 \\
           P_{4} & 0 & 1 & 1 & 0 \\
           \end{bmatrix}$$

In [46]:
# definindo a matriz rotaAerea
rotaAerea = np.array([[0,1,1,0], [1,0,1,0] , [1,0,0,1], [0,1,1,0]])

In [47]:
# imprimindo a matriz rotaAerea
print("A matriz rotaAerea é:\n\n{}".format(rotaAerea))

A matriz rotaAerea é:

[[0 1 1 0]
 [1 0 1 0]
 [1 0 0 1]
 [0 1 1 0]]


Se comunicando diretamente temos:

- $P_{1} -> P_{2}$
- $P_{1} -> P_{3}$
- $P_{2} -> P_{1}$
- $P_{2} -> P_{3}$
- $P_{3} -> P_{1}$
- $P_{3} -> P_{4}$
- $P_{4} -> P_{2}$
- $P_{4} -> P_{3}$

Agora vamos ver a comunicação em dois passos:

In [48]:
# definindo a matriz de rotaAerea_2passos para uma comunicação em dois passos, elevando-a 
# na segunda potência
rotaAerea_2passos = np.linalg.matrix_power(rotaAerea,2)

In [49]:
# imprimindo a matriz rotaAerea_2passos com dois passos
print("A matriz com dois passos é:\n\n{}".format(rotaAerea_2passos))

A matriz com dois passos é:

[[2 0 1 1]
 [1 1 1 1]
 [0 2 2 0]
 [2 0 1 1]]


Agora, analisando os dados dessa matriz, temos que a rota $P_{3}$ tem duas formas de se comunicar com $P_{2}$

$P_{3} -> P_{1} -> P_{2}$
###### ou
$P_{3} -> P_{4} -> P_{2}$

Ou então há duas formas da rota $P_{3}$ se comunicar com ela mesma, fato impossível na matriz inicial $rotaAerea^{1}$:

$P_{3} -> P_{1} -> P_{3}$

ou

$P_{3} -> P_{4} -> P_{3}$

E assim sucessivamente para as outras rotas.

Agora vamos ver conexões com 3 passos:

In [50]:
# realiza a terceira potência da matriz rotaAerea em rotaAerea_3passos
rotaAerea_3passos = np.linalg.matrix_power(rotaAerea, 3)

In [51]:
# imprimindo a matriz rotaAerea com 3 passos de conexão
print("A matriz com 3 passos é:\n\n{}".format(rotaAerea_3passos))

A matriz com 3 passos é:

[[1 3 3 1]
 [2 2 3 1]
 [4 0 2 2]
 [1 3 3 1]]


Agora vamos ver como a rota $P_{1}$ pode se comunicar por 3 passos com a rota $P_{2}$:

$P_{1} -> P_{3} -> P_{4} -> P_{2}$

ou

$P_{1} -> P_{3} -> P_{1} -> P_{2}$

E de mesmo modo para as outras rotas.

#### Aprenda mais Sobre Teoria dos Grafos

###### P. Feofiloff, Y. Kohayakawa, Y. Wakabayashi,   Uma Introdução Sucinta à Teoria dos Grafos,  2004.

###### J.M.S. Simões Pereira,  Matemática Discreta: Grafos, Redes, Aplicações,  Ed. Luz da Vida (Portugal), 2009.

### Alguma Dúvida? Entre em Contato Comigo:

- [Me envie um e-mail](mailto:alysson.barbosa@ee.ufcg.edu.br);