Calculando a
$$Fatoração$$ $$Cholesky$$

In [1]:
import numpy as np # importando a bibloteca numpy do Python

In [2]:
print("Progama que calcula a fatoração de uma matriz pelo método Cholesky.\n")

# variáveis que recebem a quantidade de linhas e colunas da matriz
linha = int(input("Informa a quantidade de linhas da matriz: "))
coluna = int(input("Informe a quantidade de colunas da matriz: "))

# criando uma matriz com a quantidade de linhas e colunas adequadas
matriz = np.empty([linha, coluna], dtype = float)

# estrutura de repetição for responsável por receber os elementos da matriz
for i in range(0, linha):
    for j in range(0, coluna):
        matriz[i][j] = float(input("Informe o elemento [{}][{}] da matriz: ".format(i + 1, j + 1)))
        
#imprime na tela a matriz digitada
print("A matriz digitada é:\n\n{}".format(matriz))

#imprime na tela a matriz fatorada pelo método cholesky
print("\n\nA matriz fatorada é:\n\n{}".format(np.linalg.cholesky(matriz)))

#imprime na tela a matriz transposta
print("\n\nA matriz transposta é:\n\n{}".format(matriz.transpose()))

# imprime a multiplicação da matriz fatorada com a matriz transposta
print("\n\nA multiplicação da matriz fatorada com a matriz transposta é:\n\n{}".format(np.matmul(matriz,matriz.transpose())))


Progama que calcula a fatoração de uma matriz pelo método Cholesky.

Informa a quantidade de linhas da matriz: 3
Informe a quantidade de colunas da matriz: 3
Informe o elemento [1][1] da matriz: 4
Informe o elemento [1][2] da matriz: 12
Informe o elemento [1][3] da matriz: -16
Informe o elemento [2][1] da matriz: 12
Informe o elemento [2][2] da matriz: 37
Informe o elemento [2][3] da matriz: -43
Informe o elemento [3][1] da matriz: -16
Informe o elemento [3][2] da matriz: -43
Informe o elemento [3][3] da matriz: 98
A matriz digitada é:

[[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]


A matriz fatorada é:

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


A matriz transposta é:

[[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]


A multiplicação da matriz fatorada com a matriz transposta é:

[[  416.  1180. -2148.]
 [ 1180.  3362. -5997.]
 [-2148. -5997. 11709.]]
