# Resolvendo Sistemas Lineares

Sistemas lineares é um conjunto de equações lineares, com m equações e n incógnitas. A solução de um sistema linear é a solução de todas as equações lineares.

Vamos definir um Sistema do tipo:

$$X + Y = 6$$

$$-3X + Y = 2$$

Podemos representar esses sistema linear utilizando matrizes

$$\begin{bmatrix}
         1 & 1 \\
         -3 & 1 \\
         \end{bmatrix}.\begin{bmatrix}
                               X \\
                               Y \\
                               \end{bmatrix} = \begin{bmatrix}
                                                 6 \\
                                                 2 \\
                                                 \end{bmatrix}$$

$$AX = B$$

$$A.A^{-1}.X = A^{-1}.B$$

$$X = A^{-1}.B$$

In [2]:
import numpy as np # importando a biblioteca numpy

#declarar as matrizes
A = np.array([[1,1],[-3,1]])
B = np.array([[6],[2]])

#Encontrar a inversa de A
A_inversa = np.linalg.inv(A) #Função que encontra a matriz inversa

#Encontrando X
X = np.dot(A_inversa,B) #Função que realiza mutiplicação entre matrizes sem especificador de tipo

 # X = np.linalg.solve(A,B) #Função alternativa que resolve Sistemas Lineares

In [3]:
A # imprime a matriz A dos coeficientes de X e Y

array([[ 1,  1],
       [-3,  1]])

In [4]:
A_inversa # imprime a matriz A inversa

array([[ 0.25, -0.25],
       [ 0.75,  0.25]])

In [5]:
B # imprime a matriz B resultado dos sistemas lineares

array([[6],
       [2]])

In [6]:
X # imprime a matrix X das variáveis que foram descobertas

array([[1.],
       [5.]])