# Progama que Calcula o Determinante de uma Matriz

> Em matemática, determinante é uma função matricial que associa a cada matriz quadrada um escalar. Essa função transforma essa matriz em um número real. Esta função permite saber se a matriz tem ou não inversa, pois as que não têm são precisamente aquelas cujo determinante é igual a 0. O cálculo de determinantes está ligado com o conjunto solução de um sistema linear, pois se o cálculo da matriz dos coeficientes de um sistema de equações lineares, onde o número de equações é igual o número de incógnitas (uma matriz quadrada) for um valor diferente de zero, possuímos uma única solução para o sistema, caso o valor do determinante for zero, temos um sistema possível indeterminado ou impossível.

In [1]:
import numpy as np #Importa Funções da biblioteca Numpy

qtd = int(input('Informe o ordem da matriz: ')) #Recebe a ordem da matriz

matriz = np.empty([qtd, qtd], dtype = float) #Inicializa a matriz, ainda com 'lixo de endereços de memória' nele

print('\n')

#Adiciona elementos na matriz
for i in range(0, qtd):
    for j in range(0, qtd):
        matriz[i][j] = float(input('Digite [{}][{}] da matriz: '.format(i + 1, j + 1)))

#Imprime a matriz
print('\nA matriz é:\n', matriz)

#a variável 'determinante' recebe o determinante da matriz
determinante = np.linalg.det(matriz)

#Imprime o determinante
print('\nO determinante da matriz é: {:.2f}.'.format(determinante))


Informe o ordem da matriz:  4


Digite [1][1] da matriz:  4
Digite [1][2] da matriz:  5
Digite [1][3] da matriz:  -3
Digite [1][4] da matriz:  0
Digite [2][1] da matriz:  2
Digite [2][2] da matriz:  -1
Digite [2][3] da matriz:  3
Digite [2][4] da matriz:  1
Digite [3][1] da matriz:  1
Digite [3][2] da matriz:  -3
Digite [3][3] da matriz:  2
Digite [3][4] da matriz:  1
Digite [4][1] da matriz:  0
Digite [4][2] da matriz:  2
Digite [4][3] da matriz:  -2
Digite [4][4] da matriz:  5



A matriz é:
 [[ 4.  5. -3.  0.]
 [ 2. -1.  3.  1.]
 [ 1. -3.  2.  1.]
 [ 0.  2. -2.  5.]]

O determinante da matriz é: 210.00.


|**Aprenda mais:**                                                                                                       |
|------------------------------------------------------------------------------------------------------------------------|
|- [Curso de Álgebra Linear](https://www.labma.ufrj.br/~mcabral/livros/livro-alglin/alglin-material/CursoAlgLinlivro.pdf)|
|- [Álgebra Linear - Vol 1](http://matematicaufsj.files.wordpress.com/2012/12/caderno_al_vol1.pdf)                       |
|- [Determinante, Essência da Álgebra Linear](https://www.youtube.com/watch?v=yt3eoYvGel0)                               |