# Operações Matriciais

Este progama visa realiza diversas operações básicas dada duas matrizes.

In [1]:
import numpy as np # importando a biblioteca numpy do Python (Necessário intalação: pip install numpy).

while True: # menu de escolhas do progama em um loop com uma ordem de parada
    
    print("Escolha uma das opções de operações com matrizes abaixo:")
    print("   1 - Soma entre duas matrizes.")
    print("   2 - Subtração entre duas matrizes.")
    print("   3 - Multiplicação entre duas matrizes.")
    print("   4 - Multiplicação de uma matriz por um escalar.")
    print("   5 - Sair do progama")

    while True: # loop com ordem de parada para que o progama aceite a entrada correta
        opcao = int(input("Insira uma opção abaixo: "))
        if opcao >= 1 and opcao <= 5:
            break
        else:
            print("Entrada errada. Digite novamente.")
    
    if(opcao == 5): # parar a execução do loop e, consequentemente do progama
        break
        
        
        
    if(opcao == 1 or opcao == 2): # estrutura de seleção para as opções 1 e 2
    
        ordem = int(input("Informe a ordem das matrizes: "))
        
        # inicializando as matrizes com suas devidas ordens e com lixo de memória
        A = np.empty([ordem,ordem], dtype = float) 
        B = np.empty([ordem,ordem], dtype = float)
        
        # estrutura de repetição for para implementar os elementos da matriz A
        for i in range(0, ordem):
            for j in range(0, ordem):
                A[i][j] = float(input("Digite o elemento [{}][{}] da matriz A: ".format(i + 1,j + 1)))
        
        # estrutura de repetição for para implementar os elementos da matriz B
        for i in range(0, ordem):
            for j in range(0, ordem):
                B[i][j] = float(input("Digite o elemento [{}][{}] da matriz B: ".format(i + 1, j + 1)))
    
        # estrutura de seleção if... else para realizar soma ou subtração com as duas matrizes digitadas
        if(opcao == 1):
            print("\n{}\n + \n{}\n = \n{}\n".format(A, B, A + B))
        else:
            print("\n{}\n - \n{}\n = \n{}\n".format(A, B, A - B))
    elif(opcao == 3): # estrutura de seleção caso o usuário queira multiplicar matrizes
        
        #informações das linhas e das colunas da matriz A
        linha = int(input("Informa quantas linhas sua matriz A terá: "))
        coluna = int(input("Informe quantas colunas sua matriz A terá: "))
        
        # inicializando a matriz A com lixo de memória
        A = np.empty([linha,coluna], dtype = float)
        
        # estrutura de repetição for para implementar os elementos da matriz A
        for i in range(0, linha):
            for j in range(0, coluna):
                A[i][j] = float(input("Digite o elemento [{}][{}] da matriz A: ".format(i + 1,j + 1)))
        
        # informações das linhas e das colunas da matriz B
        linha = int(input("Informa quantas linhas sua matriz B terá: "))
        coluna = int(input("Informe quantas colunas sua matriz B terá: "))
    
        # inicializando a matriz B com lixo de memória
        B = np.empty([linha,coluna], dtype = float)
        
        # estrutura de repetição for para preencher a matriz B
        for i in range(0, linha):
            for j in range(0, coluna):
                B[i][j] = float(input("Digite o elemento [{}][{}] da matriz B: ".format(i + 1, j + 1)))
        
        # realiza a multiplicação da matrix A e B
        print("\n{}\n x \n{}\n = \n{}\n".format(A,B,np.matmul(A,B)))
        
    elif(opcao == 4): # estrutura de seleção caso o usuário queira multiplicar uma matriz por um escalar
        
        # informações da linha, da coluna e de um escalar da matriz A
        linha = int(input("Informa quantas linhas sua matriz A terá: "))
        coluna = int(input("Informe quantas colunas sua matriz A terá: "))
        escalar = float(input("Informe um escalar: "))
        
        # inicializa a matriz A com lixo de memória
        A = np.empty([linha,coluna], dtype = float)
        
        # estrutura de repetição que preenche os elementos da matriz A
        for i in range(0, linha):
            for j in range(0, coluna):
                A[i][j] = float(input("Digite o elemento [{}][{}] da matriz A: ".format(i + 1,j + 1)))
        
        # multiplica o escalar pela matriz A
        print("\n{}\n x \n{}\n = \n{}\n".format(A, escalar, A * escalar))

Escolha uma das opções de operações com matrizes abaixo:
   1 - Soma entre duas matrizes.
   2 - Subtração entre duas matrizes.
   3 - Multiplicação entre duas matrizes.
   4 - Multiplicação de uma matriz por um escalar.
   5 - Sair do progama


Insira uma opção abaixo:  1
Informe a ordem das matrizes:  2
Digite o elemento [1][1] da matriz A:  1
Digite o elemento [1][2] da matriz A:  2
Digite o elemento [2][1] da matriz A:  3
Digite o elemento [2][2] da matriz A:  4
Digite o elemento [1][1] da matriz B:  5
Digite o elemento [1][2] da matriz B:  6
Digite o elemento [2][1] da matriz B:  7
Digite o elemento [2][2] da matriz B:  8



[[1. 2.]
 [3. 4.]]
 + 
[[5. 6.]
 [7. 8.]]
 = 
[[ 6.  8.]
 [10. 12.]]

Escolha uma das opções de operações com matrizes abaixo:
   1 - Soma entre duas matrizes.
   2 - Subtração entre duas matrizes.
   3 - Multiplicação entre duas matrizes.
   4 - Multiplicação de uma matriz por um escalar.
   5 - Sair do progama


Insira uma opção abaixo:  2
Informe a ordem das matrizes:  2
Digite o elemento [1][1] da matriz A:  1
Digite o elemento [1][2] da matriz A:  2
Digite o elemento [2][1] da matriz A:  3
Digite o elemento [2][2] da matriz A:  4
Digite o elemento [1][1] da matriz B:  5
Digite o elemento [1][2] da matriz B:  6
Digite o elemento [2][1] da matriz B:  7
Digite o elemento [2][2] da matriz B:  8



[[1. 2.]
 [3. 4.]]
 - 
[[5. 6.]
 [7. 8.]]
 = 
[[-4. -4.]
 [-4. -4.]]

Escolha uma das opções de operações com matrizes abaixo:
   1 - Soma entre duas matrizes.
   2 - Subtração entre duas matrizes.
   3 - Multiplicação entre duas matrizes.
   4 - Multiplicação de uma matriz por um escalar.
   5 - Sair do progama


Insira uma opção abaixo:  3
Informa quantas linhas sua matriz A terá:  3
Informe quantas colunas sua matriz A terá:  2
Digite o elemento [1][1] da matriz A:  2
Digite o elemento [1][2] da matriz A:  3
Digite o elemento [2][1] da matriz A:  1
Digite o elemento [2][2] da matriz A:  0
Digite o elemento [3][1] da matriz A:  4
Digite o elemento [3][2] da matriz A:  5
Informa quantas linhas sua matriz B terá:  2
Informe quantas colunas sua matriz B terá:  2
Digite o elemento [1][1] da matriz B:  3
Digite o elemento [1][2] da matriz B:  1
Digite o elemento [2][1] da matriz B:  2
Digite o elemento [2][2] da matriz B:  4



[[2. 3.]
 [1. 0.]
 [4. 5.]]
 x 
[[3. 1.]
 [2. 4.]]
 = 
[[12. 14.]
 [ 3.  1.]
 [22. 24.]]

Escolha uma das opções de operações com matrizes abaixo:
   1 - Soma entre duas matrizes.
   2 - Subtração entre duas matrizes.
   3 - Multiplicação entre duas matrizes.
   4 - Multiplicação de uma matriz por um escalar.
   5 - Sair do progama


Insira uma opção abaixo:  4
Informa quantas linhas sua matriz A terá:  4
Informe quantas colunas sua matriz A terá:  4
Informe um escalar:  10
Digite o elemento [1][1] da matriz A:  1
Digite o elemento [1][2] da matriz A:  1
Digite o elemento [1][3] da matriz A:  1
Digite o elemento [1][4] da matriz A:  1
Digite o elemento [2][1] da matriz A:  1
Digite o elemento [2][2] da matriz A:  1
Digite o elemento [2][3] da matriz A:  1
Digite o elemento [2][4] da matriz A:  1
Digite o elemento [3][1] da matriz A:  1
Digite o elemento [3][2] da matriz A:  1
Digite o elemento [3][3] da matriz A:  1
Digite o elemento [3][4] da matriz A:  1
Digite o elemento [4][1] da matriz A:  1
Digite o elemento [4][2] da matriz A:  1
Digite o elemento [4][3] da matriz A:  1
Digite o elemento [4][4] da matriz A:  1



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
 x 
10.0
 = 
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]

Escolha uma das opções de operações com matrizes abaixo:
   1 - Soma entre duas matrizes.
   2 - Subtração entre duas matrizes.
   3 - Multiplicação entre duas matrizes.
   4 - Multiplicação de uma matriz por um escalar.
   5 - Sair do progama


Insira uma opção abaixo:  5
