# Matriz Inversa
#### A matriz inversa ou matriz invertível é um tipo de matriz quadrada, ou seja, que possui o mesmo número de linhas (m) e colunas (n). Ela ocorre quando o produto de duas matrizes resulta numa matriz identidade de mesma ordem (mesmo número de linhas e colunas).

#### Referência: Álgebra Linear com aplicações / Anton Howard e Chris Rorres; trad. Claus Ivo Doering. - 8. ed. - Porto Alegre: Bookman, 2001.

###### Definição
Dada uma matriz quadrada **A**, se pudermos encontrar uma matriz **B** de mesmo tamanho tal que **AB = BA = I**, então diremos que **A** é **invertível** e que **B** é uma **inversa** de **A**. Se não puder ser encontrada uma tal matriz **B** então diremos que **A** é **não-invertível** ou **singular**.

A matriz
$$A = \begin{bmatrix}
              a & b \\
              c & d \\
              \end{bmatrix}$$
é invertível se **ad - bc &ne; 0** ou **det(A) &ne; 0**, caso em que a inversa é dada pela fórmula
$$A^{-1} = \frac{1}{ad-bc}\begin{bmatrix}
                                  d & -b \\
                                  -c & a \\
                                  \end{bmatrix} = \begin{bmatrix}
                                                          \frac{d}{ad-bc} & \frac{-b}{ad-bc} \\
                                                          \frac{-c}{ad-bc} & \frac{a}{ad-bc} \\
                                                          \end{bmatrix}$$

#### Exemplo: Encontrando Matrizes Inversas com Python

Vamos agora ver como tal processo é fácil computacionalmente:

In [3]:
import numpy as np # importando a biblioteca de funções numpy

print("Progama que calcula a matriz inversa")

# variáveis que recebem a quantidade de linhas e colunas da matriz
linha = int(input("Informe a quantidade de linhas da sua matriz: "))
coluna = int(input("Informe a quantidade de colunas de sua matriz: "))

# inicializando a matriz com seu devido tamanho
matriz = np.empty([linha,coluna], dtype = float)

# estrutura de repetição for que permite introduzir os elementos da matriz
for i in range(0, linha):
    for j in range(0, coluna):
        matriz[i][j] = float(input("Insira o elemento [{}][{}] da matriz: ".format(i + 1, j + 1)))
        
# imprime a matriz digitada na tela
print("\nA matriz digitada é:\n\n{}\n\n".format(matriz))

# calcula a matriz inversa ou retorna uma mensagem de aviso que a matriz não possui inversa
if(np.linalg.det(matriz) != 0):
    inversa = np.linalg.pinv(matriz)
    #imprime a matriz inversa
    print("A matriz inversa é:\n\n{}\n\n".format(inversa))
else:
    print("\nA matriz não é inversível.")

Progama que calcula a matriz inversa


Informe a quantidade de linhas da sua matriz:  3
Informe a quantidade de colunas de sua matriz:  3
Insira o elemento [1][1] da matriz:  3
Insira o elemento [1][2] da matriz:  0
Insira o elemento [1][3] da matriz:  2
Insira o elemento [2][1] da matriz:  2
Insira o elemento [2][2] da matriz:  0
Insira o elemento [2][3] da matriz:  -2
Insira o elemento [3][1] da matriz:  0
Insira o elemento [3][2] da matriz:  1
Insira o elemento [3][3] da matriz:  1



A matriz digitada é:

[[ 3.  0.  2.]
 [ 2.  0. -2.]
 [ 0.  1.  1.]]


A matriz inversa é:

[[ 2.00000000e-01  2.00000000e-01 -6.67894241e-19]
 [-2.00000000e-01  3.00000000e-01  1.00000000e+00]
 [ 2.00000000e-01 -3.00000000e-01  8.61308896e-17]]




|**Aprenda mais:**                                                                                                       |
|------------------------------------------------------------------------------------------------------------------------|
|- [Curso de Álgebra Linear](https://www.labma.ufrj.br/~mcabral/livros/livro-alglin/alglin-material/CursoAlgLinlivro.pdf)|
|- [Álgebra Linear - Vol 1](http://matematicaufsj.files.wordpress.com/2012/12/caderno_al_vol1.pdf)                       |