# Estudando a Biblioteca Numpy

Neste notebook, vamos analisar algumas funções pertencentes a biblioteca numpy. É pertinente saber que tal biblioteca nos permite implementar ótimas aplicações computacionais em Àlgebra Linear e, através dela, reduzir o nosso trabalho em diversas situações na qual o cálculo feito de forma manual seja algo maçante.

In [133]:
import numpy as np # importando a biblioteca de funções do python

# Criando uma Matriz

In [134]:
a = np.array([10,24,34,45,56]) # iniciando um array em python

# Verificando o Tipo da Variável

In [135]:
type(a) #mostra o tipo da variável a qual a função type recebe

numpy.ndarray

# Formas de Imprimir Dados na Tela 

In [136]:
print("{}".format(a)) # pode-se imprimir algum tipo de dado dessa forma

[10 24 34 45 56]


In [137]:
a # digitar a variável no Jupyter Notebook também nos permite ver o seu conteúdo

array([10, 24, 34, 45, 56])

In [138]:
print(a) # colocar uma variável diretamente também é um formato compilável

[10 24 34 45 56]


# Trabalhando com Elementos da Matriz

In [139]:
print("{}".format(a[0])) # atente-se que na progamação, na maioria das linguagens temos um array iniciado no elemento [0][0] 

10


In [140]:
print("{}".format(a[4])) # aqui vemos o elemento 4, na terceira possição do array

56


In [141]:
print("{}".format(a[0:4])) # mostra todos os elementos do array começando na posição zero até a terceira posição
# atente-se que o último elemento de parada não é considerado no cálculo, e sim o seu antecessor

[10 24 34 45]


# Dimensões da Matriz

In [142]:
print(a.shape) # função que mostra a dimensão do array
# (linhas, colunas)

(5,)


# Matrizes de Tamanhos Diversos

In [143]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # criando um array multidimensional

In [144]:
b # imprime o array multidimensional

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [145]:
b.shape # verificando a dimensão do array

(2, 5)

In [146]:
b[1,1] # forma de verificar os elementos da matriz multidimensional

7

In [147]:
b[1][1] # outra forma de verificar os elementos da matriz multidimensional

7

In [148]:
b.shape[0] # o parâmetro de entrada zero permitirá ver a quantidade de linhas do array

2

In [149]:
b.shape[1] # o parâmetro de entrada um permitirá ver a quantidade de colunas do array

5

# Criando uma Submatriz de Outra Matriz

In [150]:
B = b[0:2, 0:3] # B recebe as linhas localizadas na posição zero e um, e colunas de zero a dois

In [151]:
B # imprime a matriz B

array([[1, 2, 3],
       [6, 7, 8]])

# Modificando Elementos das Matrizes

In [152]:
B[1,1] = 11 # nova entrada para o elemento da matriz localizado na posição B[1][1]

In [153]:
B # veja como o elemento da matriz na posição [1][1] foi modificado

array([[ 1,  2,  3],
       [ 6, 11,  8]])

# Transformando uma Matriz de Números Inteiros em Números Reais

In [154]:
A = np.array([[1.0,2,3,4,5], [1000,12,4556,788,1], [6,7,8,9,1000]])
# o fato do primeiro elemento ser um float, número real, indica que todos os outros elementos serão também do tipo float

In [155]:
A # imprime a matriz A

array([[1.000e+00, 2.000e+00, 3.000e+00, 4.000e+00, 5.000e+00],
       [1.000e+03, 1.200e+01, 4.556e+03, 7.880e+02, 1.000e+00],
       [6.000e+00, 7.000e+00, 8.000e+00, 9.000e+00, 1.000e+03]])

Os valores dos elementos da matriz são mostrados no formato de notação científica computacional

# Criando uma Matriz Identidade

In [156]:
I = np.eye(4) #observe que a matriz identidade será do tipo float
# o parâmetro de entrada é a ordem da matriz a ser trabalhada

In [157]:
I # imprime a matriz Identidade I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Criando uma Matriz de Zeros

In [158]:
np.zeros((4,4)) # interessante para inicializar uma matriz sem lixo de memória
# são dois parâmetros de entrada, relativos a quantidade de linhas e colunas, respectivamente.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [159]:
np.ones((4,2)) # mesma ideia da função acima, mas ao invés de zeros, será preenchido com valores 1
# observe que essa matriz é ideal quando trabalha-se com operações de multiplicação

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [160]:
10 * np.ones((5,2)) # multiplicando uma matriz com todos os elementos iniciados com 1 por um escalar

array([[10., 10.],
       [10., 10.],
       [10., 10.],
       [10., 10.],
       [10., 10.]])

Ou

In [161]:
np.full((5,2), 10)
# função que cria um array em que todos os seus elementos são iguais a uma constante a ser definida
# np.full((número de linhas, número de colunas), constante a ser definida na matriz)

array([[10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10]])

# Matriz Randômica

In [162]:
np.random.random((4,5)) # np.random.random((número de linhas, número de colunas))
# cria uma matriz de números aleatórios

array([[0.42083606, 0.95941351, 0.06401885, 0.78017401, 0.7120155 ],
       [0.62225936, 0.71780581, 0.90004118, 0.97840054, 0.0492477 ],
       [0.20706932, 0.36116327, 0.20142602, 0.98057699, 0.55151439],
       [0.61957399, 0.38765467, 0.79444755, 0.07645406, 0.81756038]])

# Média dos Elementos da Matriz

In [163]:
X = np.array([[1,2,3],[4,5,6]]) # criando uma matriz X
np.mean(X) # calcula a média de todos os elementos da matriz X inicializada acima

3.5

# Operações com Matrizes

In [164]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) # criando uma matriz A
B = np.array([[-1,0,1],[0,1,1],[4,4,4]]) # criando uma matriz B

In [165]:
A # imprime a matriz A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [166]:
B # imprime a matriz B

array([[-1,  0,  1],
       [ 0,  1,  1],
       [ 4,  4,  4]])

In [167]:
C = A * B # multiplicação simples de uma matriz
# OBS: só é permitido a entrada de matrizes de mesma ordem

In [168]:
C # imprime a matriz C

array([[-1,  0,  3],
       [ 0,  5,  6],
       [28, 32, 36]])

In [169]:
C = A + B # soma duas matrizes de mesma ordem

In [170]:
C # imprime a matriz C

array([[ 0,  2,  4],
       [ 4,  6,  7],
       [11, 12, 13]])

In [171]:
C = A - B # subtração de duas matrizes de mesma ordem

In [172]:
C # imprime a matriz C

array([[2, 2, 2],
       [4, 4, 5],
       [3, 4, 5]])

Podemos realizar operações utilizando a biblioteca do numpy. Um motivo para essa escolha é que podemos realizar multiplicações com matrizes de ordens diferentes, mas definidas na operação. Além disso, pode-se mudar o tipo de dados trabalhados na matriz e ainda especificar a quantidade de bytes suportadas para armazenamento de cada elemento da mesma. (Dependência dos requisitos da máquina trabalhada, mas em geral: 16 - 128 bytes).

In [173]:
C = np.multiply(A,B, dtype = float) # multiplicação de matrizes de ordem diferentes, mas com a multiplicação definida

In [174]:
C # imprime a matriz C

array([[-1.,  0.,  3.],
       [ 0.,  5.,  6.],
       [28., 32., 36.]])

In [175]:
C = np.add(A,B, dtype = np.float16) # soma as matrizes de mesma ordem

In [176]:
C # imprime a matriz C

array([[ 0.,  2.,  4.],
       [ 4.,  6.,  7.],
       [11., 12., 13.]], dtype=float16)

In [177]:
C = np.subtract(A,B, dtype = np.int32) # subtrai as matrizes de mesma ordem

In [178]:
C # imprime a matriz C

array([[2, 2, 2],
       [4, 4, 5],
       [3, 4, 5]])

In [179]:
A = np.array([[1,2,3],[4,5,6]]) # criando a matriz A
B = np.array([[1],[1],[1]]) # criando a matriz B

In [180]:
np.matmul(A,B) #outra função que realiza a multiplicação de matrizes de ordens diferentes, mas sem especificador de tipo

array([[ 6],
       [15]])

In [181]:
np.matmul(B,A) #Matriz com operação não definida, veja que a compilação não ocorrerá

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [182]:
np.dot(A,B) # outra forma de multiplicar duas matrizes

array([[ 6],
       [15]])

In [183]:
a = np.array([[1,2,3]]) # criando a matriz a
b = np.array([[4,5,6]]) # criando a matriz b

In [184]:
np.inner(a,b) 
#Um produto interno é uma generalização do produto escalar. Em um espaço vetorial, é uma maneira de multiplicar vetores 
# juntos, com o resultado dessa multiplicação sendo um escalar.

array([[32]])

In [185]:
A = np.array([[1,2,3],[3,4,5]]) # criando a matriz A
B = np.array([[1,5,7],[5,9,9]]) # criando a matriz B

In [186]:
np.tensordot(A,B) # produto tensorial de dois espaços vetoriais

array(128)

In [189]:
A = np.array([[1,2,7],[3,6,7],[8,9,0]]) # criando a matriz A

In [190]:
np.linalg.matrix_power(A,5) # função responsável por calcular a potenciação de matrizes.
# Nesse caso, A está elevada a 5º potência

array([[123235, 185759, 175273],
       [205065, 300027, 255535],
       [221333, 307524, 210945]])

# Produto Kronecker

In [191]:
A = np.array([[1,2],[3,4]]) # criando a matriz A
B = np.array([[0,5],[6,7]]) # criando a matriz B

In [193]:
np.kron(A,B) # calcula o produto kronecker de duas matrizes

array([[ 0,  5,  0, 10],
       [ 6,  7, 12, 14],
       [ 0, 15,  0, 20],
       [18, 21, 24, 28]])

# Fatoração de Cholesky

In [194]:
A = np.array([[4,12,-16],[12,37,-43],[-16,-43,98]]) # criando a matriz A

In [195]:
fatorada = np.linalg.cholesky(A) # função responsável por calcular a fatoração de cholesky

In [196]:
fatorada # imprime a matriz A

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])

In [88]:
np.matmul(fatorada,fatorada.transpose()) #provando a validade da Fatoração de Cholesky em python
# multiplica a matriz fatorada por sua transposta, obtendo a matriz A que foi fatorada

array([[  4.,  12., -16.],
       [ 12.,  37., -43.],
       [-16., -43.,  98.]])

In [197]:
A = np.array([[2,0],[0,1]]) # criando uma matriz A

In [198]:
A # imprime a matriz A

array([[2, 0],
       [0, 1]])

# Autovalores e Autovetores

In [199]:
(autovalores, autovetores) = np.linalg.eig(A) #determinando autovalores e autovetores
matrizDiagonal = np.diag(autovalores) #matriz diagonal de autovalores

A = np.matmul(np.matmul(autovetores,matrizDiagonal),np.linalg.inv(autovetores)) # A = PDP^(-1)
# obtendo novamente a matriz A através da decomposição espectral ou valores singulares

In [200]:
autovetores # autovetores da matriz A

array([[1., 0.],
       [0., 1.]])

In [201]:
matrizDiagonal # matriz diagonal

array([[2., 0.],
       [0., 1.]])

In [202]:
A # matriz de transformação linear

array([[2., 0.],
       [0., 1.]])

In [203]:
autovalores # autovalores para a matriz A

array([2., 1.])

In [204]:
np.linalg.eigvals(A) # outra forma de se obter os autovalores

array([2., 1.])

# Decomposição em Valores Singulares

In [205]:
A = np.array([[2,0],[0,1]]) # criando uma matriz A
(U,s,V) = np.linalg.svd(A)

In [206]:
U # imprime a matriz U 

array([[1., 0.],
       [0., 1.]])

In [207]:
s # imprime a matriz s

array([2., 1.])

In [208]:
V # imprime a matriz V

array([[1., 0.],
       [0., 1.]])

# Determinante de Matrizes

In [210]:
np.linalg.det(A) # determinante da matriz

2.0

# Posto da Matriz

In [211]:
np.linalg.matrix_rank(A) #posto da matriz

2

# Traço da Matriz (Soma da Diagonal)

In [212]:
np.trace(A) #traço da matriz (soma da diagonal)

3

# Sistema de Equações

In [213]:
# Vamos considerar Ax = B
A = np.array([[3], [4]]) # criando a matriz A
b = np.array([[6], [8]]) # criando a matriz b
# 3x = 6
# 4y = 8

In [214]:
X = np.matmul(np.linalg.pinv(A), b)
# realiza a multiplicação da matriz inversa de A com a matriz b

In [215]:
X # imprime a matriz X

array([[2.]])

# Matriz Inversa

In [216]:
A = np.array([[1,2],[3,4]]) # criando a matriz A

In [217]:
np.linalg.pinv(A) # imprime a matriz inversa

array([[-2. ,  1. ],
       [ 1.5, -0.5]])