# Fatoração Cholesky

Podemos simplificar o método de decomposição LU, quando a matriz é simétrica, positiva e definida. Dessa forma, usa-se a Fatoração Cholesky.

In [1]:
import numpy as np # importando a bibloteca numpy do Python
import scipy
import scipy.linalg   # importando a bibloteca scipy do Python

In [3]:
print("Progama que calcula a fatoração de uma matriz pelo método Cholesky.")

# variáveis que recebem a quantidade de linhas e colunas da matriz
linha = int(input("Informa a quantidade de linhas da matriz: "))
coluna = int(input("Informe a quantidade de colunas da matriz: "))

# criando uma matriz com a quantidade de linhas e colunas adequadas
matriz = scipy.empty([linha, coluna], dtype = float)

# estrutura de repetição for responsável por receber os elementos da matriz
for i in range(0, linha):
    for j in range(0, coluna):
        matriz[i][j] = float(input("Informe o elemento [{}][{}] da matriz: ".format(i + 1, j + 1)))

#imprime na tela a matriz digitada
print("\n\nA matriz digitada é:\n\n{}".format(matriz))

# matriz triangular inferior
L = scipy.linalg.cholesky(matriz, lower=True)
# matriz triangular superior
U = scipy.linalg.cholesky(matriz, lower=False)

# imprime a matriz triangular inferior
print("\n\nMatriz Triangular Inferior L:\n\n{}\n\n".format(L))

# imprime a matriz triangular superior
print("Matriz Triangular Superior U:\n\n{}\n\n".format(U))

# realiza a multiplicação da matriz triangular inferior com a superior, obtendo a matriz original antes da fatoração
print("A Multiplicação de LU:\n\n{}".format(np.dot(L,U)))

Progama que calcula a fatoração de uma matriz pelo método Cholesky.


Informa a quantidade de linhas da matriz:  4
Informe a quantidade de colunas da matriz:  4


c:\users\alysson\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: scipy.empty is deprecated and will be removed in SciPy 2.0.0, use numpy.empty instead
  


Informe o elemento [1][1] da matriz:  6
Informe o elemento [1][2] da matriz:  3
Informe o elemento [1][3] da matriz:  4
Informe o elemento [1][4] da matriz:  8
Informe o elemento [2][1] da matriz:  3
Informe o elemento [2][2] da matriz:  6
Informe o elemento [2][3] da matriz:  5
Informe o elemento [2][4] da matriz:  1
Informe o elemento [3][1] da matriz:  4
Informe o elemento [3][2] da matriz:  5
Informe o elemento [3][3] da matriz:  10
Informe o elemento [3][4] da matriz:  7
Informe o elemento [4][1] da matriz:  8
Informe o elemento [4][2] da matriz:  1
Informe o elemento [4][3] da matriz:  7
Informe o elemento [4][4] da matriz:  25




A matriz digitada é:

[[ 6.  3.  4.  8.]
 [ 3.  6.  5.  1.]
 [ 4.  5. 10.  7.]
 [ 8.  1.  7. 25.]]


Matriz Triangular Inferior L:

[[ 2.44948974  0.          0.          0.        ]
 [ 1.22474487  2.12132034  0.          0.        ]
 [ 1.63299316  1.41421356  2.30940108  0.        ]
 [ 3.26598632 -1.41421356  1.58771324  3.13249102]]


Matriz Triangular Superior U:

[[ 2.44948974  1.22474487  1.63299316  3.26598632]
 [ 0.          2.12132034  1.41421356 -1.41421356]
 [ 0.          0.          2.30940108  1.58771324]
 [ 0.          0.          0.          3.13249102]]


A Multiplicação de LU:

[[ 6.  3.  4.  8.]
 [ 3.  6.  5.  1.]
 [ 4.  5. 10.  7.]
 [ 8.  1.  7. 25.]]
