# Calculando Autovalores e Autovetores

Este progama pretendo mostrar um recurso computacional para conseguir calcular autovalores e autovetores a partir de uma matriz de transformação informada. Associados com uma transformação linear T estão os seus autovetores, que, como veremos, são direções especiais para esta transformação T. Por esta razão, são também conhecidos como vetores próprios ou vetores característicos de T. Aparecem em muitas aplicações, pois nos ajudam a entender mais profundamente a transformação linear T.

In [2]:
import numpy as np # importando a biblioteca numpy do Python

In [3]:
print("Progama que calcula Autovalores e Autovetores.\n")

print("Informe a quantidade de linhas e colunas da matriz de transformação: ")

# quantidade de linhas da matriz de transformação
linha = int(input("Informe a quantidade de linhas da matriz de transformação: "))

#quantidade de colunas da matriz de transformação
coluna = int(input("Informe a quantidade de colunas da matriz de transformação: "))

# inicializando uma matriz com as dimensões adequadas e de números reais
matriz = np.empty([linha, coluna], dtype = float)

# estrutura de repetição for usada para preencher os elementos da matriz
for i in range(0, linha):
    for j in range(0, coluna):
        matriz[i][j] = float(input("Informe o elemento [{}][{}] da matriz: ".format(i + 1, j + 1)))

# funão responsável por receber os autovalores e autovetores da matriz de transformação
(autovalores,autovetores) = np.linalg.eig(matriz)
matrizDiagonal = np.diag(autovalores) # calcula a matriz diagona de autovalores

# imprime a matriz na tela
print("\n\nA matriz digitada é:\n\n{}".format(matriz))

# imprime na tela os autovalores
print("\n\nAutovalores:\n\n{}\n\n".format(autovalores))

# imprime na tela a matriz diagonal de autovalores
print("Matriz Diagonal de autovalores:\n\n{}\n\n".format(matrizDiagonal))

# imprime na tela os autovetores
print("Autovetores:\n\n{}".format(autovetores))


Progama que calcula Autovalores e Autovetores.

Informe a quantidade de linhas e colunas da matriz de transformação: 


Informe a quantidade de linhas da matriz de transformação:  3
Informe a quantidade de colunas da matriz de transformação:  3
Informe o elemento [1][1] da matriz:  2
Informe o elemento [1][2] da matriz:  0
Informe o elemento [1][3] da matriz:  0
Informe o elemento [2][1] da matriz:  0
Informe o elemento [2][2] da matriz:  3
Informe o elemento [2][3] da matriz:  4
Informe o elemento [3][1] da matriz:  0
Informe o elemento [3][2] da matriz:  4
Informe o elemento [3][3] da matriz:  9




A matriz digitada é:

[[2. 0. 0.]
 [0. 3. 4.]
 [0. 4. 9.]]


Autovalores:

[11.  1.  2.]


Matriz Diagonal de autovalores:

[[11.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  2.]]


Autovetores:

[[ 0.          0.          1.        ]
 [ 0.4472136   0.89442719  0.        ]
 [ 0.89442719 -0.4472136   0.        ]]


In [4]:
# Cada coluna da matriz de autovetores corresponde a um autovalor correspondente da coluna da matriz de autovalores