# Matriz Transposta
#### A transposta de uma matriz MA é uma matriz que possui os mesmos elementos de MA, mas postos em posições diferentes. Pode-se obter transportando ordenadamente os elementos das linhas de MA para as colunas de MA transposta.

Desse modo, tendo uma matriz $MA = (ma_{ij})_{m_{x}n}$ a transposta de MA é $MA^{t} = (ma^{'}_{ji})_{n_{x}m}$.

$MA = \begin{bmatrix}
         a_{1,1} & a_{1,2} & ... & a_{1,n} \\
         a_{2,1} & a_{2,2} & ... & a_{2,n} \\
             :   &     :   &  :  &     :   \\
         a_{m,1} & a_{m,2} & ... & a_{m,n} \\
         \end{bmatrix}
MA^{t} = \begin{bmatrix}
                 a_{1,1} & a_{2,1} &  : & a_{m,1} \\
                 a_{1,2} & a_{2,2} &  : & a_{m,2} \\
                    ...  &   ...   &  : &   ...   \\
                 a_{1,n} & a_{2,n} &  : & a_{m,n} \\
                 \end{bmatrix}$

In [1]:
import numpy as np # importando a biblioteca numpy padrão do Python

In [5]:
linha = int(input("Informe quantas linhas tem sua matriz: ")) # recebe a quantidade de linhas da matriz
coluna = int(input("Informe quantas colunas tem sua matriz: ")) # recebe a quantidade de colunas da matriz

print("\n") # comandos de ir para a próxima linha

A = np.empty([linha,coluna], dtype = float) # iniciando uma matriz de números reais com linhas e colunas definidas

# estrutura for aninhada que recebe os elementos da matriz
for i in range(0, linha):
    for j in range(0, coluna):
        A[i][j] = float(input("Insira o elemento [{}][{}] da matriz: ".format(i + 1,j + 1)))

#imprime na tela a matriz original
print("\n\nA matriz digitada é:\n\n{}\n\n".format(A))

# definindo a matriz transposta com uma função do numpy
A_T = np.transpose(A) 

# imprime na tela a matriz transposta
print("A matriz transposta é:\n\n{}\n\n". format(A_T))

# definindo a matriz transposta da matriz A_T, voltando a ser a matriz A
A = np.transpose(A_T)

# imprime na tela a matriz tranposta da mesma já transposta, ou seja, retornará a matriz original
print("A matriz transposta da transpostada é:\n\n{}".format(A))

Informe quantas linhas tem sua matriz:  2
Informe quantas colunas tem sua matriz:  3


Insira o elemento [1][1] da matriz:  1
Insira o elemento [1][2] da matriz:  2
Insira o elemento [1][3] da matriz:  3
Insira o elemento [2][1] da matriz:  4
Insira o elemento [2][2] da matriz:  5
Insira o elemento [2][3] da matriz:  6




A matriz digitada é:

[[1. 2. 3.]
 [4. 5. 6.]]


A matriz transposta é:

[[1. 4.]
 [2. 5.]
 [3. 6.]]


A matriz transposta da transpostada é:

[[1. 2. 3.]
 [4. 5. 6.]]


|**Aprenda mais:**                                                                                                       |
|------------------------------------------------------------------------------------------------------------------------|
|- [Curso de Álgebra Linear](https://www.labma.ufrj.br/~mcabral/livros/livro-alglin/alglin-material/CursoAlgLinlivro.pdf)|
|- [Álgebra Linear - Vol 1](http://matematicaufsj.files.wordpress.com/2012/12/caderno_al_vol1.pdf)                       |