# Calculando o Produto Kronecker

Em matemática, o produto Kronecker, às vezes denotado por ⊗, é uma operação em duas matrizes de tamanho arbitrário, resultando em uma matriz de blocos. É uma generalização do produto externo de vetores para matrizes e fornece a matriz do produto tensorial em relação a uma escolha padrão de base.

In [1]:
import numpy as np # importando a biblioteca numpy do Python

In [2]:
print("Progama que calcula o produto kronecker de duas matrizes.\n\n")

# quantidade de linhas e colunas da matriz A
linha = int(input("Informe as linhas da matriz A: "))
coluna = int(input("Informe as colunas da matriz A: "))

# inicializando a matriz A com as linha e colunas adequadas
A = np.empty([linha,coluna], dtype = float)

# estrutura de repetição for para dar entrada nos elementos da matriz A
for i in range(0, linha):
    for j in range(0, coluna):
        A[i][j] = float(input("Insira o elemento [{}][{}] da matriz A: ".format(i + 1, j + 1)))

# quantidade de linhas e colunas da matriz B
linha = int(input("\nInforme as linhas da matriz B: "))
coluna = int(input("Informe as colunas da matriz B: "))

# inicializando a matriz A com as linha e colunas adequadas
B = np.empty([linha,coluna], dtype = float)

# estrutura de repetição for para dar entrada nos elementos da matriz B
for i in range(0, linha):
    for j in range(0, coluna):
        B[i][j] = float(input("Insira o elemento [{}][{}] da matriz B: ".format(i + 1, j + 1)))

# imprime na tela a matriz A
print("A matriz A é:\n\n{}\n\n".format(A))

# imprime na tela a matriz B
print("A matriz B é:\n\n{}\n\n".format(B))

# imprime na tela o produto Kronecker
print("O produto Kronecker é:\n\n{}".format(np.kron(A,B)))

Progama que calcula o produto kronecker de duas matrizes.




Informe as linhas da matriz A:  2
Informe as colunas da matriz A:  3
Insira o elemento [1][1] da matriz A:  1
Insira o elemento [1][2] da matriz A:  -4
Insira o elemento [1][3] da matriz A:  7
Insira o elemento [2][1] da matriz A:  -2
Insira o elemento [2][2] da matriz A:  3
Insira o elemento [2][3] da matriz A:  3

Informe as linhas da matriz B:  4
Informe as colunas da matriz B:  4
Insira o elemento [1][1] da matriz B:  8
Insira o elemento [1][2] da matriz B:  -9
Insira o elemento [1][3] da matriz B:  -6
Insira o elemento [1][4] da matriz B:  5
Insira o elemento [2][1] da matriz B:  1
Insira o elemento [2][2] da matriz B:  -3
Insira o elemento [2][3] da matriz B:  -4
Insira o elemento [2][4] da matriz B:  7
Insira o elemento [3][1] da matriz B:  2
Insira o elemento [3][2] da matriz B:  8
Insira o elemento [3][3] da matriz B:  -8
Insira o elemento [3][4] da matriz B:  -3
Insira o elemento [4][1] da matriz B:  1
Insira o elemento [4][2] da matriz B:  2
Insira o elemento [4][3] da matri

A matriz A é:

[[ 1. -4.  7.]
 [-2.  3.  3.]]


A matriz B é:

[[ 8. -9. -6.  5.]
 [ 1. -3. -4.  7.]
 [ 2.  8. -8. -3.]
 [ 1.  2. -5. -1.]]


O produto Kronecker é:

[[  8.  -9.  -6.   5. -32.  36.  24. -20.  56. -63. -42.  35.]
 [  1.  -3.  -4.   7.  -4.  12.  16. -28.   7. -21. -28.  49.]
 [  2.   8.  -8.  -3.  -8. -32.  32.  12.  14.  56. -56. -21.]
 [  1.   2.  -5.  -1.  -4.  -8.  20.   4.   7.  14. -35.  -7.]
 [-16.  18.  12. -10.  24. -27. -18.  15.  24. -27. -18.  15.]
 [ -2.   6.   8. -14.   3.  -9. -12.  21.   3.  -9. -12.  21.]
 [ -4. -16.  16.   6.   6.  24. -24.  -9.   6.  24. -24.  -9.]
 [ -2.  -4.  10.   2.   3.   6. -15.  -3.   3.   6. -15.  -3.]]
