# Estudando a Biblioteca Numpy

#### Neste notebook, vamos analisar algumas funções pertencentes a biblioteca numpy. É pertinente saber que tal biblioteca nos permite implementar ótimas aplicações computacionais em Àlgebra Linear e, através dela, reduzir o nosso trabalho em diversas situações na qual o cálculo feito de forma manual seja algo maçante.

In [92]:
import numpy as np # importando a biblioteca de funções do python

|**Criando uma Matriz**|
|----------------------|

In [93]:
M = np.array([10,24,34,45,56]) # iniciando um array em python

|**Verificando o Tipo da Variável**|
|----------------------------------|

In [94]:
type(M) #mostra o tipo da variável a qual a função type recebe

numpy.ndarray

|**Formas de Imprimir Dados na Tela**|
|------------------------------------|

In [95]:
print("{}".format(M)) # pode-se imprimir algum tipo de dado dessa forma

[10 24 34 45 56]


In [96]:
M # digitar a variável no Jupyter Notebook também nos permite ver o seu conteúdo

array([10, 24, 34, 45, 56])

In [97]:
print(M) # colocar uma variável diretamente também é um formato compilável

[10 24 34 45 56]


|**Trabalhando com Elementos da Matriz**|
|---------------------------------------|

In [98]:
print("{}".format(M[0])) 
# atente-se que na progamação, na maioria das linguagens temos um array iniciado no elemento [0][0] 

10


In [99]:
print("{}".format(M[4])) # aqui vemos o elemento 4, na terceira possição do array

56


In [100]:
print("{}".format(M[0:4])) 
# mostra todos os elementos do array começando na posição zero até a terceira posição
# atente-se que o último elemento de parada não é considerado no cálculo, e sim o seu antecessor

[10 24 34 45]


|**Dimensões da Matriz**|
|-----------------------|

In [101]:
print(M.shape) 
# função que mostra a dimensão do array
# (linhas, colunas)

(5,)


|**Matrizes de Tamanhos Diversos (arrays multidimensionais)**|
|------------------------------------------------------------|

In [102]:
MD = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # criando um array multidimensional

In [103]:
print("{}".format(MD)) # imprime o array multidimensional

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [104]:
MD.shape # verificando a dimensão do array

(2, 5)

In [105]:
MD[1,1] # forma de verificar os elementos da matriz multidimensional

7

In [106]:
MD[1][1] # outra forma de verificar os elementos da matriz multidimensional

7

In [107]:
MD.shape[0] # o parâmetro de entrada zero permitirá ver a quantidade de linhas do array

2

In [108]:
MD.shape[1] # o parâmetro de entrada um permitirá ver a quantidade de colunas do array

5

|**Criando uma Submatriz de Outra Matriz**|
|-----------------------------------------|

In [109]:
subMD = MD[0:2, 0:3] 
# subMD recebe as linhas localizadas na posição zero e um, e colunas de zero a dois
# atente-se que o último digito de parada é desconsiderado

In [110]:
print("{}".format(subMD)) # imprime a matriz subMD

[[1 2 3]
 [6 7 8]]


|**Modificando Elementos das Matrizes**|
|--------------------------------------|

In [111]:
MD[1,1] = 11 # nova entrada para o elemento da matriz localizado na posição MD[1][1]

In [112]:
print("{}".format(MD)) # veja como o elemento da matriz na posição [1][1] foi modificado

[[ 1  2  3  4  5]
 [ 6 11  8  9 10]]


|**Transformando uma Matriz de Números Inteiros em Números Reais**|
|-----------------------------------------------------------------|

In [113]:
MR = np.array([[1.0,2,3,4,5], [1000,12,4556,788,1], [6,7,8,9,1000]])
# o fato do primeiro elemento ser um float, número real, indica que todos os outros elementos serão também do tipo float

In [114]:
print("{}".format(MR)) # imprime a matriz MR
# Os valores dos elementos da matriz são mostrados no formato de notação científica computacional

[[1.000e+00 2.000e+00 3.000e+00 4.000e+00 5.000e+00]
 [1.000e+03 1.200e+01 4.556e+03 7.880e+02 1.000e+00]
 [6.000e+00 7.000e+00 8.000e+00 9.000e+00 1.000e+03]]


|**Criando uma Matriz Identidade**|
|---------------------------------|

In [115]:
I = np.eye(4) #observe que a matriz identidade será do tipo float
# o parâmetro de entrada é a ordem da matriz a ser trabalhada

In [116]:
print("{}".format(I)) # imprime a matriz Identidade I

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


|**Criando uma Matriz de Zeros**|
|-------------------------------|

In [117]:
Z = np.zeros((4,4)) # interessante para inicializar uma matriz sem lixo de memória
# são dois parâmetros de entrada, relativos a quantidade de linhas e colunas, respectivamente.
# caso tal matriz seja manipulada por algum procedimento de multiplicação, essa inicialização não é uma boa escolha

In [118]:
print("{}".format(Z)) # imprimindo a matriz Z

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


|**Criando uma Matriz de Uns**|
|-------------------------------|

In [119]:
U = np.ones((4,2)) 
# mesma ideia da função acima, mas ao invés de zeros, será preenchido com valores 1
# observe que essa matriz é ideal quando trabalha-se com operações de multiplicação

In [120]:
print("{}".format(U)) # imprime a matriz U

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [121]:
10 * U
# multiplicando uma matriz com todos os elementos iniciados com 1 por um escalar

array([[10., 10.],
       [10., 10.],
       [10., 10.],
       [10., 10.]])

Ou

In [122]:
U = np.full((5,2), 10)
# função que cria um array em que todos os seus elementos são iguais a uma constante a ser definida
# np.full((número de linhas, número de colunas), constante a ser definida na matriz)

In [123]:
print("{}".format(U)) #imprime a matriz U

[[10 10]
 [10 10]
 [10 10]
 [10 10]
 [10 10]]


|**Matriz Randômica**|
|--------------------|

In [124]:
R = np.random.random((4,5)) # np.random.random((número de linhas, número de colunas))
# cria uma matriz de números aleatórios

In [125]:
print("{}".format(R)) # imprime a matriz R

[[0.22713023 0.71650888 0.68631372 0.40922479 0.78302245]
 [0.73126168 0.70399383 0.21533931 0.63350483 0.78617113]
 [0.16668591 0.69494935 0.69021198 0.42039054 0.42013399]
 [0.21246477 0.37482442 0.9424475  0.60936176 0.04459337]]


|**Média dos Elementos da Matriz**|
|---------------------------------|

In [126]:
X = np.array([[1,2,3],[4,5,6]]) # criando uma matriz X

In [127]:
np.mean(X) # calcula a média de todos os elementos da matriz X inicializada acima

3.5

|**Operações com Matrizes**|
|--------------------------|

In [128]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) # criando uma matriz A
B = np.array([[-1,0,1],[0,1,1],[4,4,4]]) # criando uma matriz B

In [129]:
print("{}".format(A)) # imprime a matriz A

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [130]:
print("{}".format(B)) # imprime a matriz B

[[-1  0  1]
 [ 0  1  1]
 [ 4  4  4]]


In [131]:
A * B 
# multiplicação simples de uma matriz
# OBS: só é permitido a entrada de matrizes de mesma ordem

array([[-1,  0,  3],
       [ 0,  5,  6],
       [28, 32, 36]])

In [132]:
A + B # soma duas matrizes de mesma ordem

array([[ 0,  2,  4],
       [ 4,  6,  7],
       [11, 12, 13]])

In [133]:
A - B # subtração de duas matrizes de mesma ordem

array([[2, 2, 2],
       [4, 4, 5],
       [3, 4, 5]])

In [134]:
B - A # subtração de duas matrizes de mesma ordem

array([[-2, -2, -2],
       [-4, -4, -5],
       [-3, -4, -5]])

>Podemos realizar operações utilizando a biblioteca do numpy. Um motivo para essa escolha é que podemos realizar multiplicações com matrizes de ordens diferentes, mas definidas na operação. Além disso, pode-se mudar o tipo de dados trabalhados na matriz e ainda especificar a quantidade de bytes suportadas para armazenamento de cada elemento da mesma. (Dependência dos requisitos da máquina trabalhada, mas em geral: 16 - 128 bytes).

In [135]:
np.multiply(A,B, dtype = float) # multiplicação de matrizes de ordem diferentes, mas com a multiplicação definida

array([[-1.,  0.,  3.],
       [ 0.,  5.,  6.],
       [28., 32., 36.]])

In [136]:
np.add(A,B, dtype = np.float16) # soma as matrizes de mesma ordem

array([[ 0.,  2.,  4.],
       [ 4.,  6.,  7.],
       [11., 12., 13.]], dtype=float16)

In [137]:
np.subtract(A,B, dtype = np.int32) # subtrai as matrizes de mesma ordem

array([[2, 2, 2],
       [4, 4, 5],
       [3, 4, 5]])

In [138]:
np.subtract(B,A, dtype = np.int32) # subtrai as matrizes de mesma ordem

array([[-2, -2, -2],
       [-4, -4, -5],
       [-3, -4, -5]])

In [139]:
A = np.array([[1,2,3],[4,5,6]]) # criando a matriz A
B = np.array([[1],[1],[1]]) # criando a matriz B

In [140]:
np.matmul(A,B) #outra função que realiza a multiplicação de matrizes de ordens diferentes, mas sem especificador de tipo

array([[ 6],
       [15]])

In [141]:
np.matmul(B,A) #Matriz com operação não definida, veja que a compilação não ocorrerá

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

> Cuidado, pois mesmo o código estando digitado corretamente, operações matemáticas podem não estar definidas, resultando em erros fatais ou não fatais pelo compilador.

In [142]:
np.dot(A,B) # outra forma de multiplicar duas matrizes

array([[ 6],
       [15]])

In [143]:
a = np.array([[1,2,3]]) # criando a matriz a
b = np.array([[4,5,6]]) # criando a matriz b

In [144]:
np.inner(a,b) 
#Um produto interno é uma generalização do produto escalar. Em um espaço vetorial, é uma maneira de multiplicar vetores 
# juntos, com o resultado dessa multiplicação sendo um escalar.

array([[32]])

In [145]:
A = np.array([[1,2,3],[3,4,5]]) # criando a matriz A
B = np.array([[1,5,7],[5,9,9]]) # criando a matriz B

In [146]:
np.tensordot(A,B) # produto tensorial de dois espaços vetoriais

array(128)

In [147]:
A = np.array([[1,2,7],[3,6,7],[8,9,0]]) # criando a matriz A

In [148]:
np.linalg.matrix_power(A,5) # função responsável por calcular a potenciação de matrizes.
# Nesse caso, A está elevada a 5º potência

array([[123235, 185759, 175273],
       [205065, 300027, 255535],
       [221333, 307524, 210945]])

|**Produto Kronecker**|
|---------------------|

In [149]:
A = np.array([[1,2],[3,4]]) # criando a matriz A
B = np.array([[0,5],[6,7]]) # criando a matriz B

In [150]:
np.kron(A,B) # calcula o produto kronecker de duas matrizes

array([[ 0,  5,  0, 10],
       [ 6,  7, 12, 14],
       [ 0, 15,  0, 20],
       [18, 21, 24, 28]])

|**Fatoração de Cholesky**|
|-------------------------|

In [151]:
A = np.array([[4,12,-16],[12,37,-43],[-16,-43,98]]) # criando a matriz A

In [152]:
fatorada = np.linalg.cholesky(A) # função responsável por calcular a fatoração de cholesky

In [153]:
fatorada # imprime a matriz A

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])

In [154]:
np.matmul(fatorada,fatorada.transpose()) #provando a validade da Fatoração de Cholesky em python
# multiplica a matriz fatorada por sua transposta, obtendo a matriz A que foi fatorada

array([[  4.,  12., -16.],
       [ 12.,  37., -43.],
       [-16., -43.,  98.]])

In [155]:
A = np.array([[2,0],[0,1]]) # criando uma matriz A

In [156]:
A # imprime a matriz A

array([[2, 0],
       [0, 1]])

|**Autovalores e Autovetores**|
|-----------------------------|

In [157]:
(autovalores, autovetores) = np.linalg.eig(A) #determinando autovalores e autovetores
matrizDiagonal = np.diag(autovalores) #matriz diagonal de autovalores

A = np.matmul(np.matmul(autovetores,matrizDiagonal),np.linalg.inv(autovetores)) # A = PDP^(-1)
# obtendo novamente a matriz A através da decomposição espectral ou valores singulares

In [158]:
autovetores # autovetores da matriz A

array([[1., 0.],
       [0., 1.]])

In [159]:
matrizDiagonal # matriz diagonal

array([[2., 0.],
       [0., 1.]])

In [160]:
A # matriz de transformação linear

array([[2., 0.],
       [0., 1.]])

In [161]:
autovalores # autovalores para a matriz A

array([2., 1.])

In [162]:
np.linalg.eigvals(A) # outra forma de se obter os autovalores

array([2., 1.])

|**Decomposição em Valores Singulares**|
|--------------------------------------|

In [163]:
A = np.array([[2,0],[0,1]]) # criando uma matriz A
(U,s,V) = np.linalg.svd(A)

In [164]:
U # imprime a matriz U 

array([[1., 0.],
       [0., 1.]])

In [165]:
s # imprime a matriz s

array([2., 1.])

In [166]:
V # imprime a matriz V

array([[1., 0.],
       [0., 1.]])

|**Determinante de Matrizes**|
|----------------------------|

In [167]:
np.linalg.det(A) # determinante da matriz

2.0

|**Posto da Matriz**|
|-------------------|

In [168]:
np.linalg.matrix_rank(A) #posto da matriz

2

|**Traço da Matriz (Soma da Diagonal)**|
|--------------------------------------|

In [169]:
np.trace(A) #traço da matriz (soma da diagonal)

3

|**Sistema de Equações**|
|-----------------------|

In [170]:
# Vamos considerar Ax = B
A = np.array([[3], [4]]) # criando a matriz A
b = np.array([[6], [8]]) # criando a matriz b
# 3x = 6
# 4y = 8

In [171]:
X = np.matmul(np.linalg.pinv(A), b)
# realiza a multiplicação da matriz inversa de A com a matriz b

In [172]:
X # imprime a matriz X

array([[2.]])

|**Matriz Inversa**|
|------------------|

In [173]:
A = np.array([[1,2],[3,4]]) # criando a matriz A

In [174]:
np.linalg.pinv(A) # imprime a matriz inversa

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

#### Aprenda mais

- [numpy.org](https://numpy.org/)

- [scipy.org](https://www.scipy.org/)

- [Listas de Exercícios - Álgebra Linear (prof. Edmar Candeia Gurjão)](http://ecandeia.dee.ufcg.edu.br/disciplinas)