# Calculando Matriz Inversa

In [2]:
import numpy as np # importando a biblioteca de funções numpy

print("Progama que calcula a matriz inversa")

# variáveis que recebem a quantidade de linhas e colunas da matriz
linha = int(input("Informe a quantidade de linhas da sua matriz: "))
coluna = int(input("Informe a quantidade de colunas de sua matriz: "))

# inicializando a matriz com seu devido tamanho
matriz = np.empty([linha,coluna], dtype = float)

# estrutura de repetição for que permite introduzir os elementos da matriz
for i in range(0, linha):
    for j in range(0, coluna):
        matriz[i][j] = float(input("Insira o elemento [{}][{}] da matriz: ".format(i + 1, j + 1)))
        
# imprime a matriz digitada na tela
print("\nA matriz digitada é:\n\n{}\n\n".format(matriz))

# calcula a matriz inversa
inversa = np.linalg.pinv(matriz)

#imprime a matriz inversa
print("A matriz inversa é:\n\n{}\n\n".format(inversa))

Progama que calcula a matriz inversa


Informe a quantidade de linhas da sua matriz:  3
Informe a quantidade de colunas de sua matriz:  3
Insira o elemento [1][1] da matriz:  1
Insira o elemento [1][2] da matriz:  2
Insira o elemento [1][3] da matriz:  3
Insira o elemento [2][1] da matriz:  0
Insira o elemento [2][2] da matriz:  1
Insira o elemento [2][3] da matriz:  4
Insira o elemento [3][1] da matriz:  0
Insira o elemento [3][2] da matriz:  0
Insira o elemento [3][3] da matriz:  1



A matriz digitada é:

[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]


A matriz inversa é:

[[ 1.00000000e+00 -2.00000000e+00  5.00000000e+00]
 [-2.32263640e-16  1.00000000e+00 -4.00000000e+00]
 [ 1.44375748e-16 -4.60256926e-17  1.00000000e+00]]


