# Calculando a Matriz Transposta

In [2]:
import numpy as np # importando a biblioteca numpy padrão do C++

In [4]:
linha = int(input("Informe quantas linhas tem sua matriz: ")) # recebe a quantidade de linhas da matriz
coluna = int(input("Informe quantas colunas tem sua matriz: ")) # recebe a quantidade de colunas da matriz

matriz = np.empty([linha,coluna], dtype = float) # iniciando uma matriz de números reais com linhas e colunas definidas

# estrutura for aninhada que recebe os elementos da matriz
for i in range(0, linha):
    for j in range(0, coluna):
        matriz[i][j] = float(input("Insira o elemento [{}][{}] da matriz: ".format(i + 1,j + 1)))

#imprime na tela a matriz original
print("\n\nA matriz digitada é:\n\n{}\n\n".format(matriz))

# imprime na tela a matriz transposta
print("A matriz transposta é:\n\n{}\n\n". format(np.transpose(matriz)))

# imprime na tela a matriz tranposta da mesma já transposta, ou seja, retornará a matriz original
print("A matriz transposta da transpostada é:\n\n{}".format(np.transpose(np.transpose(matriz))))

Informe quantas linhas tem sua matriz:  6
Informe quantas colunas tem sua matriz:  6
Insira o elemento [1][1] da matriz:  1
Insira o elemento [1][2] da matriz:  2
Insira o elemento [1][3] da matriz:  3
Insira o elemento [1][4] da matriz:  4
Insira o elemento [1][5] da matriz:  5
Insira o elemento [1][6] da matriz:  6
Insira o elemento [2][1] da matriz:  7
Insira o elemento [2][2] da matriz:  8
Insira o elemento [2][3] da matriz:  9
Insira o elemento [2][4] da matriz:  10
Insira o elemento [2][5] da matriz:  11
Insira o elemento [2][6] da matriz:  12
Insira o elemento [3][1] da matriz:  13
Insira o elemento [3][2] da matriz:  14
Insira o elemento [3][3] da matriz:  15
Insira o elemento [3][4] da matriz:  16
Insira o elemento [3][5] da matriz:  17
Insira o elemento [3][6] da matriz:  18
Insira o elemento [4][1] da matriz:  19
Insira o elemento [4][2] da matriz:  20
Insira o elemento [4][3] da matriz:  21
Insira o elemento [4][4] da matriz:  22
Insira o elemento [4][5] da matriz:  23
Insi



A matriz digitada é:

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]
 [13. 14. 15. 16. 17. 18.]
 [19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30.]
 [31. 32. 33. 34. 35. 36.]]


A matriz transposta é:

[[ 1.  7. 13. 19. 25. 31.]
 [ 2.  8. 14. 20. 26. 32.]
 [ 3.  9. 15. 21. 27. 33.]
 [ 4. 10. 16. 22. 28. 34.]
 [ 5. 11. 17. 23. 29. 35.]
 [ 6. 12. 18. 24. 30. 36.]]


A matriz transposta da transpostada é:

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]
 [13. 14. 15. 16. 17. 18.]
 [19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30.]
 [31. 32. 33. 34. 35. 36.]]
