# Estudando a Biblioteca Numpy
***
Neste módulo, vamos analisar alguns métodos pertencentes a biblioteca numpy. É pertinente saber que tal biblioteca nos permite implementar métodos numéricos em Àlgebra Linear, de modo rápido e preciso.

> `Versão do Python:` 3.x

`"NumPy é um pacote para a linguagem Python que suporta arrays e matrizes multidimensionais, possuindo uma larga coleção de funções matemáticas para trabalhar com estas estruturas."` - [numpy](https://numpy.org/)

### Importando a Biblioteca

In [1]:
import numpy as np 

### Criando uma Matriz

In [2]:
M = np.array([10,24,34,45,56]) 

### Verificando o Tipo da Variável

In [3]:
type(M) 

numpy.ndarray

In [4]:
print(M) 

[10 24 34 45 56]


### Trabalhando com Elementos da Matriz

In [5]:
print("{}".format(M[0])) 

10


In [6]:
print("{}".format(M[4]))

56


In [7]:
print("{}".format(M[0:4])) 

[10 24 34 45]


### Dimensões da Matriz

In [8]:
print(M.shape) 

(5,)


### Matrizes com mais dimensões

In [9]:
MD = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 

In [10]:
print("{}".format(MD)) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
MD.shape 

(2, 5)

### Visualizando elementos da matriz

In [12]:
MD[1,1] 

7

In [13]:
MD[1][1] 

7

In [14]:
MD.shape[0] 

2

In [15]:
MD.shape[1] 

5

### Criando uma Submatriz de Outra Matriz

In [16]:
subMD = MD[0:2, 0:3] 

In [17]:
print("{}".format(subMD)) 

[[1 2 3]
 [6 7 8]]


### Modificando Elementos das Matrizes

In [18]:
MD[1,1] = 11 

In [19]:
print("{}".format(MD)) 

[[ 1  2  3  4  5]
 [ 6 11  8  9 10]]


### Transformando uma Matriz de Números Inteiros em Números Reais

In [20]:
# o fato do primeiro elemento ser um float, número real, indica que todos os outros elementos serão também do tipo float
MR = np.array([[1.0,2,3,4,5], [1000,12,4556,788,1], [6,7,8,9,1000]])

In [21]:
print("{}".format(MR))

[[1.000e+00 2.000e+00 3.000e+00 4.000e+00 5.000e+00]
 [1.000e+03 1.200e+01 4.556e+03 7.880e+02 1.000e+00]
 [6.000e+00 7.000e+00 8.000e+00 9.000e+00 1.000e+03]]


### Criando uma Matriz Identidade

In [22]:
I = np.eye(4) 

In [23]:
print("{}".format(I)) 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Criando uma Matriz de Zeros

In [24]:
Z = np.zeros((4,4)) 

In [25]:
print("{}".format(Z)) 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Criando uma Matriz de 1s

In [26]:
U = np.ones((4,2)) 

In [27]:
print("{}".format(U)) 

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [28]:
print("{}".format(U * 10)) # multiplicação por um escalar

[[10. 10.]
 [10. 10.]
 [10. 10.]
 [10. 10.]]


In [29]:
U = np.full((5,2), 10) # outra forma de definir uma matriz de 1s multiplicada por um escalar

In [30]:
print("{}".format(U)) 

[[10 10]
 [10 10]
 [10 10]
 [10 10]
 [10 10]]


### Matriz Randômica

In [31]:
R = np.random.random((4,5)) # gera uma matriz com valores aleatórios

In [32]:
print("{}".format(R)) 

[[0.26000138 0.39089893 0.904526   0.97424014 0.71690065]
 [0.45488197 0.15040118 0.61285715 0.2440388  0.35228807]
 [0.65954555 0.51509763 0.91592963 0.69034736 0.68927103]
 [0.95392847 0.21745955 0.49925365 0.06144697 0.28882509]]


### Operações numéricas com uma matriz

In [33]:
X = np.array([[1,2,3],[4,5,6]])  

In [34]:
print(np.mean(X)) # média
print(np.std(X)) # desvio padrão
print(np.sum(X)) # soma dos elementos
# [...]

3.5
1.707825127659933
21


### Operações com Matrizes

In [35]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
B = np.array([[-1,0,1],[0,1,1],[4,4,4]]) 

In [36]:
A * B # multiplicação de elemento a elemento 

array([[-1,  0,  3],
       [ 0,  5,  6],
       [28, 32, 36]])

In [37]:
A + B # soma de elemento a elemento 

array([[ 0,  2,  4],
       [ 4,  6,  7],
       [11, 12, 13]])

In [38]:
A - B # subtração de elemento a elemento 

array([[2, 2, 2],
       [4, 4, 5],
       [3, 4, 5]])

In [39]:
B - A # subtração de elemento a elemento

array([[-2, -2, -2],
       [-4, -4, -5],
       [-3, -4, -5]])

> - `As operações acima podem ser resolvidas utilizando o numpy`

In [40]:
np.multiply(A,B, dtype = float) # multiplicação de elemento a elemento

array([[-1.,  0.,  3.],
       [ 0.,  5.,  6.],
       [28., 32., 36.]])

In [41]:
np.add(A,B, dtype = np.float16) # soma de matrizes elemento a elemento

array([[ 0.,  2.,  4.],
       [ 4.,  6.,  7.],
       [11., 12., 13.]], dtype=float16)

In [42]:
np.subtract(A,B, dtype = np.int32) # subtração de elemento a elemento

array([[2, 2, 2],
       [4, 4, 5],
       [3, 4, 5]], dtype=int32)

In [43]:
np.subtract(B,A, dtype = np.int32) # subtração de elemento a elemento

array([[-2, -2, -2],
       [-4, -4, -5],
       [-3, -4, -5]], dtype=int32)

In [44]:
A = np.array([[1,2,3],[4,5,6]]) 
B = np.array([[1],[1],[1]]) 

In [45]:
np.matmul(A,B) # multiplicação matricial linha x coluna

array([[ 6],
       [15]])

In [46]:
np.matmul(B,A) # observe que a operação não está definida 

ValueError: ignored

> - `Cuidado, pois mesmo o código estando digitado corretamente, operações matemáticas podem não estar definidas.`

In [47]:
np.dot(A,B) # outra forma de realizar multiplicação matricial linha x coluna

array([[ 6],
       [15]])

In [48]:
a = np.array([[1,2,3]]) 
b = np.array([[4,5,6]]) 

In [49]:
np.inner(a,b) # produto interno

array([[32]])

In [50]:
A = np.array([[1,2,3],[3,4,5]]) 
B = np.array([[1,5,7],[5,9,9]]) 

In [51]:
np.tensordot(A,B) # produto tensorial

array(128)

In [52]:
A = np.array([[1,2,7],[3,6,7],[8,9,0]]) 

In [53]:
np.linalg.matrix_power(A,5) # elevando os elementos da matriz a uma potência n

array([[123235, 185759, 175273],
       [205065, 300027, 255535],
       [221333, 307524, 210945]])

### Produto Kronecker

In [54]:
A = np.array([[1,2],[3,4]]) 
B = np.array([[0,5],[6,7]]) 

In [55]:
np.kron(A,B) # produto kronecker

array([[ 0,  5,  0, 10],
       [ 6,  7, 12, 14],
       [ 0, 15,  0, 20],
       [18, 21, 24, 28]])

### Fatoração de Cholesky

In [56]:
A = np.array([[4,12,-16],[12,37,-43],[-16,-43,98]]) 

In [57]:
fatorada = np.linalg.cholesky(A) 

In [58]:
fatorada  # realizando a fatoração de cholesky

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])

In [59]:
np.matmul(fatorada,fatorada.transpose()) 
# == provando a validade da Fatoração de Cholesky ==
# multiplica a matriz fatorada por sua transposta, obtendo a matriz A que foi fatorada

array([[  4.,  12., -16.],
       [ 12.,  37., -43.],
       [-16., -43.,  98.]])

### Autovalores e Autovetores

In [60]:
A = np.array([[2,0],[0,1]])

In [61]:
# == determinando autovalores e autovetores ==
autovalores, autovetores = np.linalg.eig(A) 
# == matriz diagonal de autovalores ==
matrizDiagonal = np.diag(autovalores) 

# == obtendo novamente a matriz A através da decomposição espectral ou valores singulares ==  A = PDP^(-1)
A = np.matmul(np.matmul(autovetores,matrizDiagonal),np.linalg.inv(autovetores)) 

In [62]:
autovetores 

array([[1., 0.],
       [0., 1.]])

In [63]:
matrizDiagonal 

array([[2., 0.],
       [0., 1.]])

In [64]:
A 

array([[2., 0.],
       [0., 1.]])

In [65]:
autovalores

array([2., 1.])

In [66]:
np.linalg.eigvals(A) # outra forma de se obter os autovalores

array([2., 1.])

### Decomposição em Valores Singulares

In [67]:
A = np.array([[2,0],[0,1]]) 
(U,s,V) = np.linalg.svd(A) # decompondo em valores singulares

In [68]:
U

array([[1., 0.],
       [0., 1.]])

In [69]:
s 

array([2., 1.])

In [70]:
V 

array([[1., 0.],
       [0., 1.]])

### Determinante de Matrizes


In [71]:
np.linalg.det(A) # determinante da matriz

2.0

### Posto da Matriz

In [72]:
np.linalg.matrix_rank(A) # posto da matriz

2

### Traço da Matriz (Soma da Diagonal)

In [73]:
np.trace(A) # traço da matriz (soma da diagonal)

3

### Resolução de Sistema de Equações

In [74]:
# Vamos considerar Ax = B
A = np.array([[3], [4]])
b = np.array([[6], [8]])

# == 3x = 6 == 
# == 4y = 8 ==

In [75]:
X = np.matmul(np.linalg.pinv(A), b) # realiza a multiplicação da matriz inversa de A com a matriz b

In [76]:
X 

array([[2.]])

### Matriz Inversa

In [77]:
A = np.array([[1,2],[3,4]]) 

In [78]:
np.linalg.pinv(A) # matriz inversa

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Observe que o pacote [numpy](https://numpy.org/) abrange uma série de problemas relativos a álgebra linear. Não se preocupe em decorar todos os problemas, o própio site do numpy oferece uma boa documentação para cada uma das implementações. O mais adequado é que o usuário entenda como é que funciona o fluxo de organização do numpy e, conforme for precisando resolver determinadas operações, buscar na documentação a possível solução. Observe também que o numpy abrange algumas otimizações computacionais, como vectorization, indexing e broadcasting. Recomendo produndamente que você pesquise os conceitos de cada uma dessas otimizações. Além disso, em problemas da área da inteligência artificial, isso economiza tempo e poder computacional.

### Alguma Dúvida? Entre em Contato Comigo: [Me envie um e-mail](mailto:alysson.barbosa@ee.ufcg.edu.br)

### Extra
***
- [Código aberto numpy](https://github.com/numpy/numpy)