# Matriz Inversa
#### A matriz inversa ou matriz invertível é um tipo de matriz quadrada, ou seja, que possui o mesmo número de linhas (m) e colunas (n). Ela ocorre quando o produto de duas matrizes resulta numa matriz identidade de mesma ordem (mesmo número de linhas e colunas).

##### Referência: Álgebra Linear com aplicações / Anton Howard e Chris Rorres; trad. Claus Ivo Doering. - 8. ed. - Porto Alegre: Bookman, 2001.

### Definição

Dada uma matriz quadrada **A**, se pudermos encontrar uma matriz **B** de mesmo tamanho tal que **AB = BA = I**, então diremos que **A** é **invertível** e que **B** é uma **inversa** de **A**. Se não puder ser encontrada uma tal matriz **B** então diremos que **A** é **não-invertível** ou **singular**.

A matriz

$$A = \begin{bmatrix}
              a & b \\
              c & d \\
              \end{bmatrix}$$

é invertível se **ad - bc &ne; 0** ou **det(A) &ne; 0**, caso em que a inversa é dada pela fórmula

$A^{-1} = \frac{1}{ad-bc}\begin{bmatrix}
                                  d & -b \\
                                  -c & a \\
                                  \end{bmatrix} = \begin{bmatrix}
                                                          \frac{d}{ad-bc} & \frac{-b}{ad-bc} \\
                                                          \frac{-c}{ad-bc} & \frac{a}{ad-bc} \\
                                                          \end{bmatrix}$

### Exemplo: Encontrando Matrizes Inversas com Python

Vamos agora ver como tal processo é fácil computacionalmente:

In [1]:
# importando a biblioteca de funções numpy
import numpy as np 

In [2]:
# função que calcula a matriz inversa
def inversa():

    print("Progama que calcula a matriz inversa")

    # variáveis que recebem a quantidade de linhas e colunas da matriz
    linha = int(input("Informe a quantidade de linhas da sua matriz: "))
    coluna = int(input("Informe a quantidade de colunas de sua matriz: "))

    # inicializando a matriz com seu devido tamanho
    matriz = np.empty([linha,coluna], dtype = float)

    # estrutura de repetição for que permite introduzir os elementos da matriz
    for i in range(0, linha):
        for j in range(0, coluna):
            matriz[i][j] = float(input("Insira o elemento [{}][{}] da matriz: ".format(i + 1, j + 1)))

    # imprime a matriz digitada na tela
    print("\nA matriz digitada é:\n\n{}\n\n".format(matriz))

    # calcula a matriz inversa ou retorna uma mensagem de aviso que a matriz não possui inversa
    if(np.linalg.det(matriz) != 0):
        inversa = np.linalg.pinv(matriz)
        #imprime a matriz inversa
        print("A matriz inversa é:\n\n{}\n\n".format(inversa))
    else:
        print("\nA matriz não é inversível.")
        
    # função não retorna nenhum valor
    return None

In [3]:
# imprimindo a função inversa
inversa()

Progama que calcula a matriz inversa


Informe a quantidade de linhas da sua matriz:  3
Informe a quantidade de colunas de sua matriz:  3
Insira o elemento [1][1] da matriz:  1
Insira o elemento [1][2] da matriz:  5
Insira o elemento [1][3] da matriz:  6
Insira o elemento [2][1] da matriz:  2
Insira o elemento [2][2] da matriz:  5
Insira o elemento [2][3] da matriz:  8
Insira o elemento [3][1] da matriz:  2
Insira o elemento [3][2] da matriz:  5
Insira o elemento [3][3] da matriz:  7



A matriz digitada é:

[[1. 5. 6.]
 [2. 5. 8.]
 [2. 5. 7.]]


A matriz inversa é:

[[-1.00000000e+00 -1.00000000e+00  2.00000000e+00]
 [ 4.00000000e-01 -1.00000000e+00  8.00000000e-01]
 [-1.58676765e-16  1.00000000e+00 -1.00000000e+00]]




### Alguma Dúvida? Entre em Contato Comigo:

- [Me envie um e-mail](mailto:alysson.barbosa@ee.ufcg.edu.br);